source/howto/zephyr-mcuboot-keys.rst, source/other/hawkbit-mqtt-system.rst, source/reference/zephyr-zmp.rst, source/tutorial/basic-system.rst, source/tutorial/dtls-system.rst
A few tweaks related to zmp changes being made since going public in other repositories (https://github.com/foundriesio/zmp-build/pull/2)
- the default build directory is now `build`, not `outdir`
- lwm2m devices use zmp:xx:yyyy when registering with mgmt.foundries.io
- other miscellany
=> Public reorg

source/reference/linux-targets.rst
The .otaimg file is .ota-ext4 now.
=> reference: linux-targets: fix generic rv64 target image

extensions/rpi3.py, source/howto/zephyr-boards.rst, source/tutorial/installation-zephyr.rst
Use the microPlatform version for github artifacts urls.
=> extensions/rpi3: use mp version for github artifacts

source/conf.py, source/tutorial/dtls-system.rst
This is the simplest for now since pyocd-flashtool (which is now obsolete) can flash the .bin in the right place.
We need to rewrite this to use a west command that generates a .hex instead (not yet available)
=> dtls-system: fix build / flash instructions for reel_board

source/reference/linux-ota.rst
We now use the aktualizr upstream sentinel file for knowing when the
device needs a reboot, so reflect that in our docs.
=> linux-ota: update need reboot sentinel path

source/customer-factory/updating-the-core.rst
To eliminate confusion / name collision later, let's call the script:
update-factory-manifest
=> customer-factory: rename factory manifest update script

source/community-factory/using.rst
The actual tag that we use for master branch builds that are not
promoted is "postmerge".
=> community-factory: post-merge -> postmerge

source/conf.py, source/index.rst
The third changes, that link to foundries.io website, only works with a recent version of sphinx. I'm not sure which version is being used to build the docs.
=> Docs updates

source/customer-factory/source-code.rst
=> customer factory: Add note on how to skip CI builds

source/customer-factory/managing.rst
No need to restart aklite service after registration.  It's done
automagically now.
=> customer-factory: managing: remove aklite restart

source/reference/linux-targets.rst
=> linux-targets: differentiate LPD4-EVK and D4-EVK

source/customer-factory/updating-the-core.rst
git revert HEAD does not actually do what we say it does.
=> update-the-core: use correct git cmd

.jobserv.yml, requirements.txt
Most sphinx projects have a requirements.txt at the root of their doctree to list sphinx extensions and their versions, currently that's just hidden in the form of a pip install command in jobserv that is pasted twice and doesn't have versions for the packages.
Jobserv will now run `pip install -r ./requirements.txt` and if we need to add extensions they'll be added to `requirements.txt` instead of updating the `jobserv.yml`
I've based the versions in requirements.txt on the latest, since that's what I have been using on my machine and seemingly has no regressions in the html output from what I see hosted online now. However, the actual versions that are being used by jobserv are not listed anywhere. 
```
sphinx-rtd-theme==0.5.0
sphinx==3.1.2
sphinxcontrib-contentui==0.2.5
```
=> sphinx: add requirements.txt to keep track of dependencies

source/conf.py
Forgot to enable it in #66
This is for fancy tabs that let us handle multiple cases, i.e macos vs win10 vs linux instructions.
=> sphinx: enable sphinx-tab plugin

source/_static/theme_overrides.css, source/conf.py
Currently the docs are a little bit hard to read on a larger monitor, since the docs scale horizontally infinitely and have no limit. As an example I've used @munoz0raul's excellent AWS docs to show the effect this has. This does not effect layouts on smaller screens, it still scales dynamically in that context.
=> sphinx: limit the page width and also center it

source/reference/compose-apps.rst
Following this guide verbatim leads to an error, since the example py script contains no shebang:
```
create failed: container_linux.go:345: starting container process caused "exec: \"/usr/local/bin/app.py\": permission denied": unknown
```
This example works fine after https://github.com/foundriesio/docs/commit/551bd6eaa3b9612fb7f4d7c29cb9e224ee929d54 and this PR is present.
=> fix compose-apps.rst, doesn't explicitly use python for Dockerfile

source/getting-started/create-compose-app/index.rst, source/index.rst
This section details how to enable the shellhttpd default example and configure your device to update to the target produced by the build process.
Additionally, I would like to add an "advanced example" section below that can be revealed by clicking on the title that details a more custom application, such as Mosquitto or Nodered, so that the user can begin tinkering with the factory sources.
=> [WIP] getting-started: create-compose-app

source/customer-factory/managing.rst, source/reference/advanced-tagging.rst, source/reference/factory-definition.rst
This section of the docs predates our factory definition support and was
incorrect. This rewords things to match how it can be done now.
=> tagging: Update section for Factory Definition support

source/conf.py
* Remove HTML tags from project name as they are not
correctly rendered in the page title and breaks
Google Search API, returning bad characters.
Signed-off-by: Milo Casagrande <milo@foundries.io>
=> fix: Fix project name

source/customer-factory/source-code.rst
* Use sphinx `:samp:` role to treat links with variables
as not hyperlinkable, to prevent browsers showing them
as real links.
Signed-off-by: Milo Casagrande <milo@foundries.io>
=> fix: Fix broken links to sources and hub

source/getting-started/create-compose-app/index.rst, source/getting-started/register-device/index.rst, source/index.rst
Initially, when creating getting-started, I noticed that this step of creating the compose app wouldn't necessarily be dependent upon flashing the device. However, I ended up explaining some steps that *are* dependent on flashing the device, such as `fioctl devices list`. Ideally, the user would be completing this step whilst their first build is being produced, since this takes time. So I will simply move this section lower in the index for now until I rewrite this section for the beta app release with better thought given to making it independent from flash-device.
=> getting-started: fix index order, dependency on flash-device

source/reference-manual/ota/advanced-tagging.rst
=> docker: Remove references to `docker-apps` - tiny nitpicking

source/getting-started/create-compose-app/index.rst, source/reference-manual/index.rst
Having a title and a top level link to the reference manual isn't very helpful. Expose the reference subsection titles are the top level for the user.
=> reference-manual: set menu depth to 2

source/reference-manual/linux/linux-building.rst, source/reference-manual/linux/linux-dev-container.rst
Show how to use a shared folder when running the docker container, and
improve the standard build instructions to make it more clear.
=> linux: improve building from scratch instructions

source/getting-started/create-compose-app/index.rst, source/glossary/index.rst, source/reference-manual/docker/compose-apps.rst, source/reference-manual/ota/device-tags.rst, source/reference-manual/troubleshooting/troubleshooting.rst, source/user-guide/fioctl/index.rst
--factory flag is now mandatory when using 'fioctl targets'.
=> getting-started: update flags on fioctl targets

source/reference-manual/security/secure-elements/secure-element.050.rst
Expand acronyms on the security chapter for better comprehension.
=> reference-manual::security:: Expand acronyms

source/getting-started/register-device/index.rst
This warns that all apps will be enabled by default in the lmp-device-register section.
This is also referenced in the create-compose-app section
=> getting-started::register-device: warn that all apps will be enabled by default

source/glossary/index.rst
- Updates targets.json to reference TUF Metadata. 
- Updates MACHINE to mention that we officially support boards in the list that is referenced.
=> glossary: update terminology definitions

source/reference-manual/ota/ota-architecture.rst
- Fixes some grammatical mistakes in the OTA section
=> reference-manual::ota fix grammar

source/reference-manual/security/offline-keys.rst
'fioctl keys rotate' is deprecated in favor of 'fioctl keys rotate-root'
=> reference-manual::security: rotate -> rotate-keys

source/reference-manual/linux/linux-building.rst, source/reference-manual/qemu/arm64.rst, source/reference-manual/qemu/riscv64.rst, source/reference-manual/qemu/x86_64.rst
This PR includes patches to:
* suggest reader to go to the 'Register your device' after booting a QEMU machine.
* Include the instruction on how to download and build a factory locally.
In case there is a way to avoid replicating the same text in all QEMU machine pages, please, let me know.
=> Suggestion for QEMU sections and Factory local build

source/_static/csv/supported-boards.csv
We have merged the TI am64xx-sk into the LmP so this is to document that it is supported.
=> Add the TI AM64xx-sk board to the supported list

source/reference-manual/security/secure-boot-imx.rst
=> security: Fix broken NXP link for HAB documentation

source/reference-manual/security/factory-registration-ref.rst, source/reference-manual/security/ota-security.rst
=> Add documentation for manufacturing device registration

source/reference-manual/ota/configuring.rst
By providing example output of fioctl config log, it is easy to see what the effect of --reason is.
=> reference-manual::ota: show effect of --reason

source/_static/csv/supported-boards.csv, source/reference-manual/boards/imx6-prepare.rst, source/reference-manual/boards/imx6ull.rst, source/reference-manual/security/imx-generic-custom-keys.rst, source/reference-manual/security/secure-boot-imx6ullevk-sec.rst, source/reference-manual/security/secure-boot.rst
It does not include the instructions from [readme.md](https://github.com/foundriesio/meta-lmp/blob/master/meta-lmp-bsp/recipes-support/mfgtool-files/mfgtool-files/imx6ullevk-sec/readme.md) file, but points the reader to follow them from the file.
It also adds the instructions to create and replace the UUU scripts.
It does **not** include instructions on how to create keys.
=> imx6ullevk-sec: Instructions for enabling secure book on a imx6ullevk baord

requirements.txt
After starting get the error:
Could not import extension sphinx_toolbox.confval (exception: No module named 'cachecontrol')
Couldn't find why it is happening but figure out that the new version fixed that.
=> sphinx-toolbox: updating version

source/reference-manual/security/factory-registration-ref.rst, source/user-guide/configure-lmp/index.rst
How to enable production devices registration by default on LmP creating
a bbappend to change PACKAGEGROUP default.
=> user-guide:configure-lmp: How to enable PRODUCTION=on on LmP

mkdocs/docs/reference-manual/linux/linux-oss-compliance.md
This PR is the conversion of #220 to MkDocs
The only significant change is that the subsections:
INCOMPATIBLE_LICENSE
IMAGE_LICENSE_CHECKER_ROOTFS_BLACKLIST
are real subsections now.
And I hope the conversion is as expected
=> rm: linux: Add a section on OSS compliance

source/getting-started/flash-device/index.rst
Removing the warning "Do not skip the final steps. Functionality with
the serial console enabled is severely degraded." to avoid redundancy.
=> flash-device: wifi: Remove Raspberry Warning

source/tutorials/configuring-and-sharing-volumes/dynamic-configuration-file.rst, source/tutorials/creating-first-target/what-is-a-target.rst
Andy suggested that in the newer tutorials because most customer will have just one Factory.
The ideia is to make it simple for new users.
=> tutorials: Removing -f <factory>

source/reference-manual/security/imx-generic-custom-keys.rst, source/reference-manual/security/secure-boot-imx6ullevk-sec.rst, source/reference-manual/security/secure-elements/secure-element.050.rst
- fix typo in secure-boot-imx6ullevk-sec.rst
- fix a directory name and a path to the fuse key in imx-generic-custom-keys.rst
- fix a link to the "NXP SE05x T=1 Over I2C Specification" document (https://foundriesio.atlassian.net/browse/FS-843)
=> A pack of non-critical fixes

source/_static/csv/supported-boards.csv, source/reference-manual/boards/am64xx-sk.rst, source/reference-manual/boards/apalis-imx6.rst, source/reference-manual/boards/beagleboneblack.rst, source/reference-manual/boards/imx8mm.rst, source/reference-manual/boards/imx8mq.rst, source/reference-manual/boards/intel-corei7-intaller.rst, source/reference-manual/boards/raspberrypi.rst, source/reference-manual/boards/stm32mp1.rst, source/reference-manual/qemu/arm64.rst, source/reference-manual/qemu/riscv64.rst
Add a link from Supported Machines page to board flashing instruction
pages.
=> reference-manual: add cross reference to board pages

source/reference-manual/linux/preloaded-images.rst
This patch adds a section in the preload-images describing how to start
compose apps early in the boot sequence, not waiting for the
aktualizr-lite.
=> reference-manual: linux: Add early start recipe to preloaded images

source/_static/csv/supported-boards.csv
We support Raspberrypi-4 CM instead
=> Supported boards: Raspberrypi-3 CM is no longer supported

source/reference-manual/troubleshooting/troubleshooting.rst
=> rm: faq: add information on extending the kernel boot args for lmp-base

source/reference-manual/remote-access/wireguard.rst
This patch describes how to change vpn address on factory connected
devices.
=> reference-manual: How to change wireguard address

source/reference-manual/security/secure-elements/se050-enablement.rst
The current steps are validated with EdgeLock SE05x Plug & Trust Middleware
version (02.14.00), so fix this and include a note to contact support
when doing the se050 integration.
=> rm: security: se050-enablement: update information on middleware version

source/conf.py
Added files that are used in include directives to the `excluded_patterns` list
in `source/conf.py`.
Tested and verified fix locally.
This patch will close FFTK-1048
=> [FFTK-1048] Stop partial pages being generated

source/reference-manual/qemu/qemu-instructions.template
Added a brief explanatory note of the QEMU CLI to start the image, and
included a link to QEMU's documentation. A more detailed explanation
could always be added later.
Checked that content appeared as intended when rendered as html.
Link was checked to ensure it was correct.
This addresses Jira FFTK-1037.
=> Add high-level explanation of QEMU CLI

source/getting-started/flash-device/index.rst
Changed note from required to highly recommended and enforced by
default.
Built site locally and verified change.
This commit addresses Jira FFTK 1090
=> Change eMMC flashing note to highly recommended

source/reference-manual/linux/linux-building.rst
Updated reference-manual/linux/linux-building to note that if BUILDDIR
is used, it must still be within the lmp dir.
Compiled site locally, rendered as intended.
This applies to Jira FFTK-998
=> Add BUILDDIR path info for local builds

source/getting-started/install-fioctl/index.rst
Added information for fioctl cli install in getting started for macs running
on M1.
Checked locally, no issues found.
This applies to jira FFTK-1124
=> Update fioctl install to include darwin-arm64

source/reference-manual/security/authentication-xilinx.rst, source/reference-manual/security/offline-keys.rst
The information about the e-mail is dated, the e-mail notification no
longer contains the location to a one time download of TUF keys. This is
now possible through `fioctl keys rotate-root --initial` . The reference
to the first root key has been changed to `first` instead of `offline` .
Signed-off-by: Eric Bode <eric.bode@foundries.io>
=> security: Improved instructions on offline keys

source/reference-manual/security/device-gateway.rst
Align a type of an offline device private key with the type
used by the default/LmP registration utility (lmp-device-register).
=> rm: security: dg: align a device key type with lmp-dev-reg

source/conf.py
Our CI tries to set the LMP build to the latest "release" we have. It
was based on an ancient (pre "factory") API we have deprecated. This
change uses a better approach.
=> conf: Fix api for finding LMP build

source/reference-manual/remote-access/wireguard.rst
Until we smooth out this flow with oauth2, we need to explain this
better.
=> wireguard: Clarify token scope requirements

source/conf.py
The copyright statement's date range is hard-coded, and has now been
updated for year 2022.
Html was built locally to verify change.
No issue linked, due to this being a small catch and fix.
=> Update copyright range into 2022

source/reference-manual/troubleshooting/troubleshooting.rst
Added suggestion to check connectivity/access by using curl within a
alpine container.
This applies to Jira FFTK #1179
=> Add using curl via a container to Troubleshooting

source/reference-manual/security/secure-elements/se050-enablement.rst
The note that about boards that support se05x integration without
changes in LmP might lead to the conclusion that the change in
meta-subscriber-overrides is not needed for these boards, so move
this note to avoid this.
=> rm: security: se05x: move note to avoid confusion

source/reference-manual/troubleshooting/troubleshooting.rst, source/tutorials/customizing-the-platform/enabling-recipe.rst
Added to the troubleshooting and FAQ page as a question/answer. The
initial plan was to move it onto a seperate tutorial page, but much of
the content was found to already be existing under the platform
customization page. Did some minor changes to the existing content, and
added a link to the tutorial as well as to the systemd site.
This commit applies to Jira FFTK #1068
=> Expand on adding a systemd startup service

source/reference-manual/linux/linux-distro.rst, source/reference-manual/ota/aktualizr-lite.rst, source/user-guide/container-preloading/container-preloading.rst
Typo: aktualizr-lite.rst
Code format: linux-distro.rst
Improvements in container-preloading.rst
- Define only 'preload' to avoid mixing pre-load/preload
- Add emphasis to assembly-system-image in preloaded containers.
=> Container-preloading improvements and minor fixes

source/reference-manual/security/secure-boot-imx-habv4.rst
Our fusing scripts always use the signed spl so change
the docs accordingly.
=> rm: secure-boot-imx: refer to signed spl

source/reference-manual/ota/ci-targets.rst, source/reference-manual/ota/ota.rst, source/reference-manual/ota/targets.rst
The goal was to talk about condensed targets. However, that was
difficult without first introducing the generic concept of Targets and
then diving into "ci targets".
The generic targets doc was largely lifted from my "What a Target"
blog:
https://foundries.io/insights/blog/2020/05/14/whats-a-target/
=> ota: Add more details about targets

source/reference-manual/security/secure-elements/secure-element.050.rst
Link check was failing due to a link pointing to a non-existent external
doc page, it now references the correct page.
Ran linkcheck and viewed rendered html page to validate change.
No issue created as this was a minor fix.
=> Fix broken link in secure-elemewnt.050.rst

source/reference-manual/remote-access/wireguard.rst
We now have a much simpler way to get the VPN server configured using
oauth2
=> rm: Update wireguard configuration

source/_static/theme_overrides.css
Our html lists have looked bad for a really long time. They use the
theme's default 16px found which is bigger than our paragraph body font
making lists look pretty awkward.
=> css: Fix list spacing

source/reference-manual/boards/stm32mp1.rst
It was converted by mistake, in this case, it is a variable and not a
override.
=> stm32mp1:eula: Fix the variable name

source/reference-manual/docker/configure-docker-helper.rst, source/reference-manual/docker/docker.rst, source/reference-manual/factory/api-access.rst
Added a page, `reference-manual/docker/configure-docker-helper`,
updated the sections index, and included links between api-access
page and the new page.
We may want to move it elsewhere, or change some of the content of the
new page.
Checked rendered pages locally for formatting, and ran the linkcheck.
This applies to Jira FFTK 1350
=> Document use of the Docker credential helper

source/reference-manual/security/imx-generic-custom-keys.rst
These instructions cause a build error in v86, so drop this.
Error:
| install: cannot create regular file '{DEPLOYDIR}/mfgtool-files/close.uuu':
No such file or directory
=> rm: security: sec machines: drop .bbappend content

source/_static/csv/supported-boards.csv
Since [1] the machine Corstone 700 is removed.
https://git.yoctoproject.org/meta-arm/commit/meta-arm-bsp/conf/machine?h=kirkstone&id=92490b7fc5cd002f13337860ed34a608d4fba24b
=> supported-boards: Remove Corstone 700

README.md, requirements.txt, source/conf.py
The MyST parser extension was added to `requirements.txt` and
`source/conf.py`. It was also noted in the README. Details will be added
to CONTRIBUTING.md at a later date to summarize syntax. Please check in
with a Foundries.io technical writer before adding markdown.
Site was built and checked locally. Testing markdown pages were added
alongside restructured text, and included in the sidebar, before being
removed. No issues detected with simple markdown.
No issues to associate with this commit.
=> Add support for rendering Markdown

source/reference-manual/troubleshooting/troubleshooting.rst
Customers expect the new user to be shown in /etc while they show
in /usr/lib, so add a note for that.
=> rm: faq: add note for adding a new user

source/reference-manual/qemu/arm.rst, source/reference-manual/qemu/arm64.rst, source/reference-manual/qemu/generic-prepare.template, source/reference-manual/qemu/qemu-instructions.template, source/reference-manual/qemu/qemu-ssh.template, source/reference-manual/qemu/riscv64.rst, source/reference-manual/qemu/x86_64.rst
As part of regular documentation maintenance, tidied up the pages and
templates, changed admonitions where appropriate, applied semantic newlines,
removed words that could be removed. No major changes to content made.
For QA: ran linkcheck, built and viewed content for intended rendering.
It may be wise to validate steps for each QEMU machine as part of a
separate task.
=>  Clean up reference manual section on QEMU images

source/reference-manual/security/secure-boot-imx-habv4.rst, source/reference-manual/security/secure-elements/secure-element.050.rst, source/user-guide/fioctl/index.rst
The goal is to make sure we cover any variable being converted in Kirkstone.
While on this, change some words.
Sensitive review based on https://inclusivenaming.org/word-lists/no-change/
For I2C terms, following I2C revision 7 from https://www.nxp.com/docs/en/user-guide/UM10204.pdf
**master**: we are still converting the `master` branch on each repository, the documentation will follow the repository accordingly.
=> rm:ug: Sensitive review based on Kirkstone update

.github/pull_request_template.md
Added a section to the top of the PR template presenting checkboxes to
mark the "readiness" of the merge.
No QA steps taken, no related issue.
Current PR template does not include options to state readiness, and was suggested in PR #380. 
Adding this option explicitly may prevent undesired merges.
=> Add readiness to PR template

source/getting-started/install-fioctl/index.rst, source/index.rst
Changes made to grammar, word usage, and admonition types. The sidebar
index page was modified so that install-fioctl came before the git page.
The git page assumes the user is familiar with generating a key,
which install-fioctl covers.
QA steps included running checklink and build, along with spellcheck.
The validity of the steps was not checked.
=> Cleanup getting-started install-fioctl page

source/reference-manual/security/security.rst
The section header for overview was changed from top to level two.
Changes did not appear until a clean build was done.
For QA steps, links and rendering were checked. No content change, so
a reduced set of checks performed.
This will close Jira FFTK 1617.
The Security page in the reference manual had two top level headers, so that both "Security" and "Overview" showed up at the same level in the sidebar, while the overview section also showed up as a child/page section for security. There should only be one top level header on a page.
_This could include potential issues, …
=> Remove RM Security:Overview from having own link in sidebar nav

source/reference-manual/linux/linux-wic-installer.rst, source/reference-manual/qemu/demo/x86_64.cast, source/reference-manual/qemu/x86_64-substitutions.inc, source/reference-manual/qemu/x86_64.rst
Prefer the ovmf.secboot.qcow2 firmware by default as that allows
enabling and using UEFI Secure Boot.
Prefer the ovmf.secboot.qcow2 firmware by default as that allows enabling and using UEFI Secure Boot.
=> qemu-x86: use ovmf.secboot.qcow2 by default

source/reference-manual/linux/linux-building.rst
Links were updated to point to available pages after YP doc site
changes.
QA: ran linkcheck.
No associated Jira issues.
linkcheck was failing due to links to Yocto Project Documentation no longer being available.
* [] Match tone and style of page/section.
=> Fix broken links to Yocto Project documentation

source/getting-started/install-fioctl/index.rst
The instruction does not work any more.
```
$ go get github.com/foundriesio/fioctl
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
$ go install github.com/foundriesio/fioctl@main
go: downloading github.com/foundriesio/fioctl v0.19.2-0.20220812084014-6d08d04faeef
go: github.com/foundriesio/fioctl@main (in github.com/foundriesio/fioctl@v0.19.2-0.20220812084014-6d08d0 …
```
=> gs: Remove fioctl installation from source code

source/reference-manual/docker/configure-docker-helper.rst
Two changes were made:
The use of sudo for the symlink step was changed to note that it is
specific to that cmd invocation specifically.
An additional admonition was added to draw attention to the need for
the user to belong to the docker group.
QA steps: make Linkcheck was ran, and the rendered html was checked.
Vale was ran to lint the content.
No related issue.
A Slack discussion in infrastructure pointed out the need to clarify user permissions for docker, specifically around the docker config helper.
If I didn't quite hit the mark, let me know and I will make further changes.
=> Clarify user permissions for Docker config helper

source/_static/csv/supported-boards.csv, source/reference-manual/boards/boards.rst, source/reference-manual/boards/stm32mp15-disco.rst
Use kirkstone naming for STM32MP15 Discovery Kit:
s/stm32mp1-disco/stm32mp15-disco/g.
=> rm: boards: stm32mp15-disco: use kirkstone naming

source/reference-manual/security/secure-boot-stm32mp1.rst
Because it's indented, it renders as part of the code block above it.
This is a trivial change so the normal PR template is skipped.
=> Fix incorrect indentation of .. warning:: label

source/conf.py
The new path is https://docs.foundries.io/latest/.
Note that this only addresses the issue of going forward, and does not completely solve the issue of older versions showing up in search results.
Built and rendered locally without issue.
No issues to tag, as this is a relatively minor change. (picked out from a larger effort)
This is part of a larger effort to address older doc versions from coming up in searches.
The commit does **not** address the issue with past releases however.
* [] Avoid changing any header associated with a link/reference.
* [] Step through instructions (or ask someone to do so).
=> Add latest to canonical url path

source/reference-manual/docker/containers.rst
As per: https://github.com/foundriesio/ci-scripts/pull/216
* [*] Merge (pending reviews)
A one-liner fix.
=> rm: Fix docker info on common base image

source/reference-manual/security/authentication-xilinx.rst
Updated reference-manual/security/authentication-xilinx to link to a listing of related documents, as the pdf we had been linking to is no longer available at that address, and could not be found. The information should be findable in the new link however.
Ran link-check and rendered the page. No errors were found.
This commit applies to Jira FFTK #1880
The broken link has been causing all doc builds to fail during `make linkcheck`. Changed the link to where I believe the information can be found still, if not with a bit more work. This will need to be verified. 
=> Fix broken link reference in rm:security

source/user-guide/el2g.rst
Signed-off-by: Milo Casagrande <milo@foundries.io>
As per marketing request, we should remove Slack references when used for support purposes.
It should be a trivia change, no QA tests have been run.
=> fix: remove slack references

source/tutorials/compose-app/compose-app-docker-container-image.rst, source/tutorials/creating-first-target/commit-and-push-our-changes.rst
Simple change to hub-ui for looking at images instead of hub.foundries.io
There is a split in the domain of `hub.foundries.io` into `hub-ui.foundries.io` for the UI/UX and `hub-auth.foundries.io` that just does the authorization part. This change reflects that new split.
=> fix(docker): Change to hub-ui

source/_templates/layout.html
We need to have a cookie consent element in place to be able to serve google analytics.
This is a temporary solution until we have a cookie consent element.
Signed-off-by: Milo Casagrande <milo@foundries.io>
=> fix(layout): remove google analytics

source/getting-started/git-config/index.rst
Added the manual steps one can take in order to make sure you are not blocked when faced with an error. Aside from that I changed the fioctl code to try and use the `uid` instead of the username.
Signed-off-by: Eric Bode <eric.bode@foundries.io>
=> fix(git): Added recovery path from error

source/user-guide/offline-update/offline-update.rst
fioctl requires token with proper scope in order to download offline update. This patch adds this detail to the offline-update page.
This patch clarifies the scope of token required to download offline update
=> offline-update: describe fioctl token scope

source/getting-started/install-fioctl/index.rst
The install-fioctl page had duplicate implicit targets; application credentials appeared both as a section name and a external hyperlink. To fix this the section title was changed to active voice, other section titles were changed to active voice where appropriate so that there would be agreement.
While updating the page, style guidelines were applied, with "fioctl" becoming "Fioctl" where appropriate, and the first instance displaying the trademark symbol.
Reference targets no longer in use were also removed.
QA: Ran linkcheck and checked rendered content for appropriate rendering. No issues were spotted.
No issues to link to, as this was a quick fix/cleanup.
General cleanup
=> Remove duplicate implicit target in install-fioctl

.vale.ini
`.vale.ini` updated to use most recent package of the Foundries.io linter style. Vale spelling was also removed; with the number of technical terms that can come up, using an additional list will require frequent updating, and can conflict with other linter rules. Additionally, all those contributing to the docs are expected to be doing spell checks independently.
QA steps: ran `vale sync` and ran vale against `README.md` a rst file in source.
=> Update Vale config to Fio-style v1.0.0 release

.vale.ini
fio-style v1.0.0 -> v1.1.0. This covers more acronym exceptions for the linter rule.
Tested with `vale sync` and a tmp file to check functionality.
No Jira issue to tag, routine task.
Routine task, does not effect documentation
=> Update fio-style package version

.github/workflows/main.yml
Adding the vale-action/reviewdog github action to run for PRs open against main. Note that it will fail on errors, more work will be needed to get suggestions and warnings posted automatically as review comments, and it is still recommended that vale is run locally against changes before opening a PR.
This was tested on a fork, so there may need to be changes (such as to the TOKEN) before it works properly under the Foundriesio account.
=> Add basic linter action for PRs

source/_templates/layout.html
Make the analytics cookie selection on by default (as per marketing), and fix the policy links to point to foundries.io website.
=> fix: cookie notice

README.md
Added a note to `README.md` that linting requires Vale version 2.16.0 or greater. There is a workaround, but in most circumstances it is likely best to be using a newer version. Also did a few quick edits to make the linters happy, and removed bit about invoking Vale with `make`, as it's no longer the recommended way.
QA Steps: ran `README.md` through linter, corrected issues found.
No issues to link, as this is just a quick update/cleanup.
Vale 2.16.0 or greater is needed to use packages, as done so by docs. Added a note to `README.md` to reflect this.
=> Clean and expand README.md

source/porting-guide/pg-spl-kernel.rst, source/reference-manual/linux/linux-kernel.rst
There are two different sections regarding "linux fragments," but only one of them shows the technical instructions on how to configure the kernel, so add the cross-reference.
Another important change is on the title, as for a lot of readers, I would expect they don't know what the term "Linux fragment" means, so I suggest another title.
While on that, fix some other minor stuff.
=> Linux fragments

source/reference-manual/security/imx-generic-custom-keys.rst
The link was changed as of 2023-03-31, with the source documentation linked to now being hosted on GitHub. The link was updated to point to the new location.
QA steps: ran linkcheck and verified the link is functional.
No issue to link, as this is a minor fix.
=> Fix broken link to imx u-boot documentation

source/user-guide/mirror-action/mirror-action.rst
It has been reported that github no longer does runs-on for 18.04
=> Move mirror-action runs-on to 20.04

source/reference-manual/linux/factory-device-reset.rst
Add main distinction between full and partial factory reset. Add clarification that at this point in time RPMB is not touched during factory reset.
Improves the documentation for the factory reset.
=> reference-manual: linux: improve factory reset docs

source/reference-manual/security/factory-keys.rst
Remove ambiguity in the documentation explaining the different keys. Adding explanation that the naming indicated where the public part is used. Also extending the documentation to indicate which part is being validated by the key.
* [ X follow best practices for commits.
=> factory-keys.rst: improve key explanations

source/index.rst, source/reference-manual/index.rst
Added `reference-manual/index.rst` as a summary/landing page for the reference manual.
Note not every topic was mentioned; the RM section itself is likely to be thinned out, as many pages are more appropriate for the user guide.
QA: ran linkcheck, checked html output in browser, ran linter.
This commit applies to:
Jira FFTK-1973
=> Add Reference Manual summary page

source/reference-manual/qemu/arm-substitutions.inc, source/reference-manual/qemu/arm64-substitutions.inc, source/reference-manual/qemu/qemu-instructions.template, source/reference-manual/qemu/riscv64-substitutions.inc, source/reference-manual/qemu/x86_64-substitutions.inc
Added instructions on resizing qemu images, focusing on fetching the existing qcow2 file, with a tip on creating one from the wic file.
QA Steps: followed instructions on a macOS arm machine to boot a qemu-arm64 image without issue. Rendered and examined html output.
This commit addresses FFTK-2424
Adds instructions for using a resizable qemu image to existing documentation.
This could also go on a separate page in the section rather than integrated as in this commit.
As the instructions for the x86-64 Qemu uses a UEFI cow2 file, I attempted to avoid confusion, however the templated nature of this section, while otherwise helpful, made this a bit more difficult. If it does seem confusing, I can rework it.
=> Add instructions on expandable Qemu disk images

source/reference-manual/boards/imx-common-board.inc, source/reference-manual/boards/imx6ul.rst, source/reference-manual/boards/imx6ull.rst, source/reference-manual/boards/imx8ulpevk.rst, source/reference-manual/boards/imx93evk.rst
Please review and let me know what you think 
The goal is to get the maximum text reuse for the flashing pages by using variables to replace some key texts.
The converted boards so far:
* imx6ulevk - https://ci.foundries.io/projects/fio-docs/builds/2244/docs/artifacts/html/reference-manual/boards/imx6ul.html
* imx6ullevk - https://ci.foundries.io/projects/fio-docs/builds/2244/docs/artifacts/html/reference-manual/boards/imx6ull.html
* imx8ulpevk - https://ci.foundries.io/projects/fio-docs/builds/2244/docs/artifacts/html/reference-manual/boards/imx8ulpevk.html
* imx93evk - https://ci.foundries.io/projects/fio-docs/builds/2244/docs/artifacts/html/reference-manual/boards/imx93evk.html
Unchanged:
* imx8mnevk
* imx8mmevk
* imx8mqevk
* apalis6
* apalis8
It uses variables to replace some texts …
=> Reorg flash page

source/porting-guide/pg-spl-kernel.rst, source/porting-guide/pg-spl-uboot-fragments.rst, source/porting-guide/pg-spl-uboot.rst, source/reference-manual/docker/restorable-apps.rst, source/reference-manual/factory/factory-definition.rst, source/reference-manual/factory/factory-sources.rst, source/reference-manual/linux/linux-oss-compliance.rst, source/reference-manual/linux/preloaded-images.rst, source/reference-manual/ota/advanced-tagging.rst, source/reference-manual/ota/static-deltas.rst, source/reference-manual/security/authentication-xilinx.rst, source/reference-manual/security/factory-registration-ref.rst, source/reference-manual/security/secure-boot-uefi.rst, source/user-guide/container-preloading/container-preloading.rst, source/user-guide/fioctl/index.rst, source/user-guide/foundriesio-rest-api/foundriesio-rest-api.rst, source/user-guide/lmp-auto-hostname/lmp-auto-hostname.rst, source/user-guide/lmp-device-auto-register/lmp-device-auto-register.rst, source/user-guide/mirror-action/mirror-action.rst
Instances where master branch should be changed to main were implemented. Not all were directly related to the Fast First Target/customer repos; links and references to meta-lmp were also updated to main.
QA steps: built html and linkcheck. As the focus was on keeping things atomic, linter warnings were ignored, as difficult as it was.
This commit addresses FFTK-2430  
This commit addresses FFTK-860
*   [ ] Draft
*   [ ] Step through instructions (or ask …
=> Update for fast first target master to main

source/reference-manual/security/cert-rotation.rst, source/reference-manual/security/imx-generic-custom-keys.rst, source/reference-manual/security/secure-boot-uefi.rst
Linkcheck encountered issues with some links. In two instances it was a simple 404 issue with a changed location of content. In the other the link functions in the browser, however linkcheck seemed to have issue with GitHub links linking to specific line numbers.
For the link in `cert-rotation.rst`, it was simply removed, as it did not feel necessary.
QA Steps: ran linkcheck
No related issues/tickets, minor quick fix.
Simple fixes to some broken links
=> Fix broken links in security section

source/getting-started/flash-device/index.rst
With FFT, the initial images provided follow a different naming pattern than before. A note was added in the getting started guide.
QA steps: checked rendered html in browser.
No related issues to link.
=> Add note on platform image names

source/reference-manual/security/factory-keys.rst
=> rm: factory-keys: Fix formating

source/getting-started/building-deploying-app/index.rst
A `seealso` admonition was added to the end of the getting started guide's build and deploy section.
QA steps: Ran linter, linkcheck, and examined html. No issues found.
This commit addresses FFTK-2620.
*   [ ] Draft
Addresses feedback from Slack discussion. It also seems like useful info to point to at the end of getting started, as it may be the next step for some.
*   [x] Step through instructions (or ask someone to do so).
*   [x] Review for …
=> Add link to customizing platform at end of gs

source/user-guide/lmp-customization/lmp-customization.rst, source/user-guide/troubleshooting/troubleshooting.rst
Added the reference to the correct location, removed from the incorrect.
QA Steps: Rendered into html and checked the new link locally.
No issues to link, quick fix.
=> Fix incorrect internal reference link

README.md
It is only updating the README to include the graphviz dependency.
I've tried to find a package to add via requirements.txt, but I could not find it _easily_. So let's keep the same logic used on the server builds and use the external graphviz.
=> README: Add graphviz installation as required package

source/getting-started/install-fioctl/index.rst
Only adding one command to explain how to test fioctl only to make sure the configuration is correct.
=> gs: fioctl: Add how to test configuration

source/user-guide/lmp-auto-hostname/lmp-auto-hostname.rst, source/user-guide/lmp-customization/lmp-customization.rst, source/user-guide/lmp-device-auto-register/lmp-device-auto-register.rst, source/user-guide/mirror-action/mirror-action.rst
Cleanup of four pages, focusing on applying style guide and simplifying language where applicable. Semantic newlines also implemented, to assist with cleanup as well.
QA Steps: Vale linter and linkcheck ran. Checked render html.
This commit applies to FFTK 988
=> Cleanup user-guide pages l-mi

source/user-guide/el2g.rst, source/user-guide/fioctl/index.rst, source/user-guide/foundriesio-rest-api/foundriesio-rest-api.rst
Three pages were cleaned up to meet style guidelines, and updated where needed.
This included removing dead internal references/links and simplifying wording. Semantic newlines were added.
Note that not all information was verified for being up to date, as the focus was primarily on style.
The issues stated in FFTK 2174 have been addressed except for item 3, which is out of our control.
QA Steps: vale linter, linkcheck, viewed rendered HTML.
This commit addresses FFTK 2527
This commit addresses FFTK 2174
This commit applies to FFTK 988
_This could include potential issues, rational for approach, …
=> Cleanup user guide sections d-f

source/user-guide/container-preloading/container-preloading.rst
Shortened a sentence where a noun is used twice.
QA steps: Checked rendered html in browser, no issues.
No Issues to link, small fix.
Very minor change to style.
=> Reduce wordiness instance

source/user-guide/account-management/account-roles.rst
Information on Account Roles and how it relates to device management was added, based of of existing information from the Team based access page.
The information will need to be verified.
QA steps: Ran linter. Checked rendered output.
This commit addresses FFTK-2603
*   [ ] Draft
_This is a basic attempt at addressing the issue, we may want to make additional changes._
*   [x] Review for …
=> Add info on Account Roles and device management

source/reference-manual/security/secure-machines.rst
The variable is deprecated since:
https://github.com/foundriesio/ci-scripts/pull/306
=> rm: security: The variable UBOOT_SIGN_ENABLE from factory is deprecated

source/reference-manual/factory/factory-definition.rst, source/reference-manual/linux/linux-oss-compliance.rst
Describe some variables and provide some references in a central place (the page where you see how to change the factory config file).
=> rm: factory definition: Describe a list of variables

source/reference-manual/factory/factory-definition.rst
The `failures_only` param option was idented to belong to `email`.
QA: Checked rendered doc, no issues.
No issues to link to, minor issue and fix.
*   [ ] Draft
*   [ ] Match tone and style of page/section.
*   [x] View HTML in a browser to check rendering.
*   [ ] Use [semantic …
=> Fix indent on factory definition page

README.md
- Correct the command for executing the requirements.
- Include two notes to guide new users and prevent potential issues.
=> (readme): small fix and add notes to help out new users

source/getting-started/install-fioctl/index.rst
See that the path where the tool is installed is `sudo curl -o /usr/local/bin/fioctl`
Therefore, this PR is a nit just to fix the instruction. 
=> (getting started): fix bin path where is installed the fioctl

source/reference-manual/qemu/qemu-instructions.template
The note provided before the command might lead users to believe that the ENV VAR will automatically be utilized by QEMU during its execution. This can be misleading, especially for those unfamiliar with QEMU or the outlined solution. Personally, the necessity of exporting this variable wasn't clear to me until I reviewed the 'targets' section.
So I would like to suggest the following changes:
**Before this PR:**
**Suggested changes in this PR**
=> (QEMU) Clarification on ENV VAR Usage

source/reference-manual/qemu/arm64.rst
It was not clear to me where could I get the flash.bin 
Also, not all arc images will have the flash.bin.
Example:
Therefore, this PR propose adding a note to try to clarify and provide as an example a command that can work in those cases.
=> (QEMU - Arm64) clarify artefacts available and used

source/reference-manual/security/device-gateway.rst
- Just add the commands in the code block to make it easier to copy and paste
- Clarify that the view should be executed after the first command to check the outcome. 
See the proposal changes:
**(Before PR)**
**(After PR)**
=> (Setting up your PKI): (Nit)Clarify command usage

source/reference-manual/qemu/arm64.rst
The line `-drive file=QEMU_VARS.fd,format=raw,if=pflash \   # Here's the added line` should not be added because I am not using it to run
=> (QEMU run) fix nit - remove line added my mistake into the example

source/reference-manual/boards/imx-common-board.inc, source/reference-manual/boards/imx6ul.rst, source/reference-manual/boards/imx6ull.rst, source/reference-manual/boards/imx8mm.rst, source/reference-manual/boards/imx8mn.rst, source/reference-manual/boards/imx8mp.rst, source/reference-manual/boards/imx8mq.rst, source/reference-manual/boards/imx8ulpevk.rst, source/reference-manual/boards/imx93evk.rst
Since https://github.com/foundriesio/meta-lmp/pull/1279 we are using compressed image in the uuu script for full image flashing.
To be merged after  https://github.com/foundriesio/meta-lmp/pull/1279 is merged
=> rm: boards: Use compressed image with mfgtool files

source/reference-manual/boards/am62xx-sk-prepare.rst, source/reference-manual/boards/am62xx-sk.rst
Update flashing instructions, as new flash.sh script is used for flash automation.
=> rm: boards: am62xx-evk: update flashing instructions

source/reference-manual/linux/linux-disk-encryption.rst
First append and then specify the target hardware, otherwise it ends up overriding the variable instead.
=> rm: linux-disk-encryption: fix append order for luks

source/reference-manual/ota/production-targets.rst
=> Production OTA: Add link for offline keys (requirement) and reason for motivation to do static deltas

source/reference-manual/linux/linux-distro.rst, source/reference-manual/qemu/qemu-instructions.template, source/user-guide/lmp-customization/lmp-customization.rst
=> Enhance Documentation: Clarifications and Helpers for Graphical Booting in QEMU

.jobserv.yml, requirements.txt, source/conf.py
Updated to latest compatible versions of packages, and updated python version for `jobserv.yml`. Myst package has remained unused, so it has been removed.
It is entirely possible that this commit may break things. No issues when checked locally.
No related issues to tag.
=> Update Sphinx Packages

source/reference-manual/linux/linux-lmp-fs.rst, source/reference-manual/linux/linux.rst
Moving this from Confluence to public docs.
=> rm: linux-lmp-fs: add page about lmp file structure

source/reference-manual/security/factory-registration-ref.rst
Improve documentation to help users better understand the purpose and relationship between the `factory-registration-ref` and the device gateway. (`to just try make it a little easier to connect the dots here`) 
=> doc: suggestion: Clarify Manufacturing Process for Device Registration

source/getting-started/emulation-with-qemu/index.rst, source/reference-manual/qemu/qemu-instructions.template
=> doc: qemu: clarify how to emulate multiple devices

source/user-guide/el2g.rst
lmp-el2go-auto-register was extended with support for generic keypairs in PR https://github.com/foundriesio/meta-lmp/pull/1307. Document this new feature, in particular that `GENERIC_KEYPAIRS` has to be set in `/etc/default/lmp-el2go-auto-register`.
=> el2g: add documentation for GENERIC_KEYPAIRS

source/user-guide/el2g.rst
*   [ ] Merge (pending reviews)
*   [ ] Draft
*   [ ] Avoid changing any header associated with a link/reference.
*   [ ] Match tone and style of page/section.
*   [ ] View HTML in a browser to check rendering.
*   [ ] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
*   [ ] follow best practices for commits.
*   [ ] Descriptive title written in the imperative.
* …
=> Revert 611 main

source/tutorials/configuring-and-sharing-volumes/copy-configuration-file-using-dockerfile.rst, source/tutorials/configuring-and-sharing-volumes/modify-shellhttpd-container.rst, source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst, source/tutorials/configuring-and-sharing-volumes/update-shellhttpd-application.rst, source/tutorials/customizing-the-platform/enabling-recipe.rst, source/tutorials/getting-started-with-docker/extra-commands.rst, source/tutorials/getting-started-with-docker/gs-docker-compose.rst, source/tutorials/working-with-tags/adapting-shellhttpd.rst, source/tutorials/working-with-tags/creating-targets.rst, source/user-guide/lmp-auto-hostname/lmp-auto-hostname.rst, source/user-guide/submodule/submodule.rst
Updated the documentation to reference vi instead of gedit for text editing steps. This change ensures broader compatibility across various Unix-like operating systems and offers a more universally available option for readers
=> Replace gedit references with vi for broader OS compatibility

source/getting-started/install-fioctl/index.rst, source/user-guide/troubleshooting/troubleshooting.rst
=> doc: fioctl symbolic link to setup git cannot be fixed

source/reference-manual/qemu/qemu-instructions.template
As the QEMU section had been cleaned up as parts of previous commits, the focus here was to address any outstanding issues. the qcow2 artifact was reported to no longer be available, so the instructions were updated to reflect this.
Output was checked in the browser.
This commit addresses FFTK-2793
This commit applies to FFTK-2732
This commit applies to FFTK 2731
=> Cleanup reference-manual qemu section

source/tutorials/customizing-the-platform/commit-and-push-recipe.rst
A mention of 'platform-devel' found in the 'customizing the platform' tutorial was replaced with 'platform-main'.
Grep'd all the tutorial for any other mentions where *not appropriate*.
No QA steps performed.
No issues to link, minor fix.
=> Remove mention of devel branch from tutorial

source/reference-manual/factory/api-access.rst, source/reference-manual/factory/ci-webhooks.rst, source/reference-manual/factory/data-retention.rst, source/reference-manual/factory/event-queues.rst, source/reference-manual/factory/factory-definition.rst, source/reference-manual/factory/factory-sources.rst, source/reference-manual/factory/factory.rst, source/reference-manual/factory/sboms.rst
Style guide lines applied. Removed link to the Yocto Project layers section which is part of the LmP reference manual; this was done to make navigation less confusing, and to keep sections focused.
The section on Factory Sources was placed before the Factory Definition, for better explanatory flow.
QA steps: Ran linter and addressed issues where possible/appropriate. Checked html output in browser, no obvious rendering issues discovered. Ran linkcheck.
This commit addresses FFTK-2790
This commit addresses FFTK-1880
This commit applies to FFTK-2732
This commit applies to FFTK-2730
This commit applies to FFTK-988
_Any thing else that a maintainer/reviewer …
=> Cleanup of factory reference manual section

source/reference-manual/boards/imx8mm.rst, source/reference-manual/boards/imx8mn.rst, source/reference-manual/boards/imx8mp.rst, source/reference-manual/boards/imx8mq.rst, source/reference-manual/boards/imx8ulpevk.rst
In some cases, the command itself was missing the first letter on the rendered html ("susb" instead of "lsusb"). In others, the command output was missing the first letter ("us 002 Device 052..." instead of "Bus 002 Device 052...").
The instructions for flashing some NXP boards in the rendered HTMLs where missing the first char in some cases. This PR fixes it.
I've verified the generated HTMLs and grepped for all cases where this was happening, fixing them all.
=> rm: Fix lsusb command in some NXP boards flashing instruction

source/conf.py, source/index.rst, source/user-guide/rotating-cert.rst
The cert rotation page in the user-guide, `cert-rotation` was renamed to `rotating-cert` to avoid sharing the name with the reference manual page.
A page redirect was added, and the index page updated.
Checked output in browser, no issues identified.
This commit addresses FFTK-2939
=> Fix cert-rotation page name duplication

source/user-guide/lmp-customization/linux-building.rst
Updated linux-building page, so that android-tools-fsutils is now android-sdk-libsparse-utils.
Small change, no QA done.
No issue opened.
*   [ ] Draft
*   [x] Step through instructions (or ask someone to do so).
*   [ ] View HTML in a browser to check rendering.
*   [ ] Use [semantic …
=> Fix build setup requirement

source/reference-manual/ota/production-targets.rst
The last example on the production-targets page had an incorrect format.
=> Correct the last example of a waves rollout

source/reference-manual/ota/advanced-tagging.rst, source/reference-manual/ota/aktualizr-lite.rst, source/reference-manual/ota/ci-targets.rst, source/reference-manual/ota/configuring.rst, source/reference-manual/ota/device-tags.rst, source/reference-manual/ota/fioconfig.rst, source/reference-manual/ota/ota-architecture.rst, source/reference-manual/ota/ota.rst, source/reference-manual/ota/production-targets.rst, source/reference-manual/ota/static-deltas.rst, source/reference-manual/ota/targets.rst, source/reference-manual/ota/update-rollback.rst
Grammar and style changes made.
Updates to content may be required.
QA: Ran linter in editor.
Checked rendered output in browser, no rendering issues spotted. Linkcheck encountering issues not believed to be associated with any changes made in this commit.
This commit addresses FFTK-2792
This commit applies to FFTK-2730
This commit applies to FFTK-2732
This commit applies to FFTK-2731
This commit applies to FFTK-1702
This commit applies to FFTK-988
=> Cleanup ota reference manual

source/reference-manual/security/device-gateway.rst, source/user-guide/device-gateway-pki/device-gateway-pki.rst, source/user-guide/rotating-cert.rst
Moved warning for `fioctl keys ca create` to device-gateway-pki page. Added info to the other two applicable pages.
QA Steps: Checked rendered output.
No issues to link.
This commit attempts to address issues discussed in slack.
The idea is to make it more clear that `fioctl keys ca create` is largely a one time only/single-use command.
=> Clarify warning for setting factory root of trust

source/reference-manual/remote-access/remote-access.rst, source/reference-manual/remote-access/wireguard.rst
The remote access section of the reference manual (wireguard) was cleaned up to adhere to the style-guide. Added additional content for troubleshooting, and worked on clarifying potential points of confusion.
QA steps: Ran link-check and linter. Checked build output, no issues found with rendering.
This commit addresses FFTK-1704
This commit addresses FFTK-2794
This commit addresses FFTK-2954
Feel free to suggest additional info or changes!
=> Cleanup wireguard reference manual

source/reference-manual/security/security.rst
Small changes made to hopefully improve readability and to adhere to the style-guide.
QA Steps: linter and linkcheck, viewed rendered output.
At least to start, the cleanup of the security section will be done page by page to keep PR reviews more manageable. It is possible that some fixes will need cross page/section work, which I will attempt to address after basic cleanup, if needed.
This commit focuses on the first overview page.
=> Cleanup security reference manual overview

source/reference-manual/linux/linux-nfs-boot.rst, source/reference-manual/linux/linux.rst
Succintly document how to NFS mount a WIC image that uses OStree.
=> rm: linux: add linux-nfs-boot information

source/reference-manual/security/factory-registration-ref.rst
Style and readability fixes applied.
The subsections had duplicate naming which I attempted to address accurately.
Viewed rendered output. Ran linter.
*   [ ] Draft
*   [ ] Avoid changing any header associated with a link/reference.
*   [x] Run `make linkcheck`.
*   [x] View HTML in a browser to check rendering.
*   [x] Use [semantic newlines](https://bobheadxi.dev/semantic-line-breaks/).
*   [x] …
=> Cleanup factory-registration security rm page

source/user-guide/lmp-customization/lmp-customization.rst
bash printf has an easy way to escape any special character.
Facilitate the life of the user creating a custom password.
=> ug: lmp-customization: add instruction to escape passwd with printf

source/user-guide/lmp-device-auto-register/lmp-device-auto-register.rst
lmp-device-auto-register script can register device with additional tags and using HSM. This patch describes how to use these options.
lmp-device-auto-register script can register device with additional tags and using HSM. This patch describes how to use these options.
=> user-guide: additional config for lmp-device-auto-register

source/reference-manual/security/imx-generic-custom-keys.rst, source/reference-manual/security/secure-machines.rst
Focus was on style and readability.
This page currently has issues with content, such as those discussed in FFTK-2841, which will require greater rework, and will be addressed separately from the cleanup effort.
QA Steps: Ran linter, spellcheck, and checked rendered html.
unsure about some changes made, feel free to question.
=> Cleanup security secure-machines page

source/reference-manual/security/boot-software-updates-imx.rst
Two typos were identified and fixed.
QA Steps: checked that html builds.
This applies to FFTK-2795
Simple patch for two typos, will merge upon successful CI build.
=> Fix typos in ``boot-software-updates-imx.rst``

source/reference-manual/security/secure-elements/se050-enablement.rst
Applied style guide rules and made minor changes for readability.
Built and checked page for correct rendering, edited with linter and spellcheck on.
*   [ ] Draft
_Only minor changes made_
*   [x] View HTML in a browser to check rendering.
*   [x] …
=> Cleanup secure-element-se05x page

source/reference-manual/factory/factory-definition.rst
It turned the current info on the TUF targets expiration configuration is not quite accurate. It suggests to use `<build-type>.params.TUF_TARGETS_EXPIRE` parameters which is rather an internal mechanism and should not be recommended for users.
The proper way to set targets metadata default validity period is through the `tuf.targets_expire_after` parameter, this is the one that we should recommend to users.
_Any thing else that a …
=> rm: factory: Add info on TUF targets expiration configuration

source/user-guide/custom-sota-client.rst
=> Document the choices of OTA operations

source/reference-manual/boards/am64xx-sk-prepare.rst
Removed link which was resulting in a 404. No suitable alternative found, and does not seem necessary.
QA Steps: Read page to make sure link could be removed without major loss of information. Ran Linkcheck and built documentation. No issues spotted.
No issues to link, minor fix.
=> Fix broken link to ti documentation

source/release-notes/release-notes.rst, source/release-notes/rn_v93.inc
Release notes for the LmP v93 release.
=> release-notes: add release notes for the v93 release

source/getting-started/building-deploying-app/index.rst, source/getting-started/flash-device/index.rst, source/getting-started/signup/index.rst, source/glossary/index.rst, source/reference-manual/factory/factory.rst, source/user-guide/account-management/account-management.rst
The glossary was cleaned up a bit, new terms added, as well as links to related topic pages.
Links to glossary terms were added in a few areas, with a focus on the 'getting started' sections.
This is the first of a handful of PR commits meant to update the glossary.
QA Steps: Ran build, examined output. No issues spotted. Linkcheck failed due to unrelated issue which has been identified and will be updated separately.
This commit addresses FFTK-3008
All PRs should be reviewed by a technical writer/documentation team and a peer.  
*   [x] Merge (pending …
=> Update general and existing glossary terms

requirements.txt
This wasn't required on x86/linux but I discovered it was required for arm/macos
=> requirements: Include requirement for setuptools

source/conf.py, source/user-guide/containers-and-docker/container-preloading.rst
Information that was on the removed
`reference-manual/linux/preloaded-images` page that did not migrate to the user-guide page was added.
QA: visually inspected html, checked with linter. No issues spotted.
No associated Ticket/Issue, as this was a quick fix.
Focus was mostly upon copying the old information and cleaning it up. Open to suggestions if context or content needs additional work. Redirect was also added. …
=> Add lost container preloading info

source/user-guide/offline-update/offline-update.rst
Add information about signing of the offline update bundle. Specifically, how to do it, and what errors to expect if the signature is invalid.
=> ug: offline-update: Add info on bundle signing

source/glossary/index.rst, source/reference-manual/security/factory-registration-ref.rst
Added terms gathered by OTA team.
QA Steps: Checked rendered HTML, no issues found. Ran linter and spellcheck.
This commit addresses FFTK-3010
=> Add OTA terms to Glossary

source/reference-manual/remote-access/wireguard.rst
Info was added to what was assumed to be the appropriate spot; will need to be reviewed, and possibly expanded upon.
QA steps: checked rendered output in browser. Edited doc with linters.
No related issue/task, quick-fix to a Customer Success request.
=> Add missing token scopes for wireguard oauth

source/user-guide/offline-update/offline-update.rst
=> ug: offline-update: Adjustments in return codes documentation

source/user-guide/lmp-customization/lmp-customization.rst
Addressed issues to more closely adhere to the style-guide.
Checked rendered output, and ran linter. No issues to report.
No associated ticket, minor fix.
=> Fix typo and style issues in lmp-customization

source/reference-manual/factory/factory-definition.rst
This commit removes 1 of 2 reference, with the other being included in PR #712.
QA Steps: Checked rendered output, no issues seen.
No related ticket, small fix.
=> Remove deprecated sstate-cache-mirror reference

source/reference-manual/boards/imx6ull.rst, source/reference-manual/boards/imx8mp.rst, source/reference-manual/boards/imx8mq.rst, source/reference-manual/boards/secure-boot-pre-flash-note.rst
Missing whitespace was causing internal doc links to not be rendered into html for some of the imx flashing instructions.
QA Steps: checked rendered output, no issues spotted.
No related ticket, minor fix
=> Fix broken refs in board flashing instructions

source/user-guide/account-management/team-based-access.rst, source/user-guide/troubleshooting/troubleshooting.rst
=> ug: faq: add troubleshooting for user permissions

source/user-guide/troubleshooting/troubleshooting.rst
=> ug: faq: add more information to debug user permissions

source/getting-started/emulation-with-qemu/index.rst, source/glossary/index.rst, source/porting-guide/pg-distro-lmp-base.rst, source/porting-guide/pg-reference.rst, source/reference-manual/factory/factory-definition.rst, source/reference-manual/linux/building-sdk.rst, source/reference-manual/linux/factory-device-reset.rst, source/reference-manual/linux/linux-disk-encryption.rst, source/reference-manual/linux/linux-kernel.rst, source/reference-manual/linux/linux-layers.rst, source/reference-manual/linux/linux-repo.rst, source/reference-manual/linux/linux-wic-installer.rst, source/reference-manual/security/boot-software-updates-imx.rst, source/reference-manual/security/imx-generic-custom-keys.rst, source/reference-manual/security/secure-boot-imx-habv4.rst, source/tutorials/customizing-the-platform/customizing-the-platform.rst, source/user-guide/custom-ci/custom-ci-for-rootfs.rst, source/user-guide/lmp-customization/linux-building.rst
Additional terms added to glossary, and references added to a number of pages. A couple typos encountered fixed.
QA steps: Checked rendered output and checked with linter.
This commit addresses FFTK-3012
This commit addresses FFTK-3011
This commit applies to FFTK-2011
=> Add platform and linux terms to glossary

source/tutorials/deploying-first-app/deploying-first-app.rst
Reference to another tutorial was broken, issue identified and fixed.
QA steps: checked rendered output to check that ref/link is working.
No related task tracking info, minor fix.
=> Fix broken ref link in deploying app tutorial

release-notes/rn_v92.md, release-notes/rn_v93.md, source/reference-manual/testing/lmp-testplan.rst
Language changed to clarify. reference to private repo removed. Link to release notes folder added, and release notes for v92 and v93 updated to include links to test results.
Other minor fixes to style applied.
QA Steps: ran link check, checked links manually, and viewed rendered html. Also ran linter. No issues to report.
No related task, quick fix.
Addresses feedback reported internally via Slack
_This could include …
=> Cleanup and fixes for lmp-testplan page

source/user-guide/containers-and-docker/configure-docker-helper.rst
Used the `important` admonition with how to locate the line to comment out to get the credential helper to work on macOS. Left out other troubleshooting steps, which can be added if warranted.
QA steps: checked rendered output in browser, ran linter.
No related tasks, quick fix.
=> Add admonition for credential helper on macOS

requirements.txt, source/_templates/searchbox.html, source/conf.py
Added search functionality.
Two api keys are exposed, with limited scope.
The search api, which is normal and required for basic search functionality.
An additional key allows for getting the list of indexes. This allows for checking if an index matching the release exists.
If no index exists, the default doc search is used.
Known issues: as a limit to the number of indexes/releases will eventually present itself, older indexes will need to be deleted. As Sphinx is static, this presents a bit of an issue. However, once version selection is implemented, older versions will be rebuilt, meaning older releases with deleted search indexes will fallback to using the default Sphinx search.
Additionally, local/PR CI builds will use a "dev" index. This will eventually be configured to use the most …
=> Add meilisearch for docs search

release-notes/rn_v94.md, source/index.rst
Release notes for the v94 release.
=> release-notes: add initial release notes for the v94 release

source/user-guide/custom-sota-client.rst
=> Custom sota dedicated repo

source/reference-manual/linux/linux-oss-compliance.rst
The license string used on the recipes is an information which constantly changing, so having it static in the documentation can lead the reader to error.
Adding the link where to find the most current regex can help.
This text can lead to an error if it's not up to date (and this has changed more than once in last 2 years). So, let's remove it and add the link instead.
While on this, fix some grammar points.
=> RM: Remove the reference for the license strings

source/user-guide/el2g.rst
Minor rST syntax issues were causing some formatting mistakes. Additional style and grammar cleanups also done.
QA Steps: Ran linter. Viewed output in browser.
No related tasks, minor fix.
Cleaned up a couple minor issues, added some links to the glossary
=> Cleanup el2g guide

Makefile, requirements.txt, source/_templates/footer.html, source/conf.py, source/glossary/index.rst, source/index.rst
Offline documentation is provided in both PDF and HTML form. As the extension used to build the PDF may come with dependency issues, it is commented out in `requirements.txt`. Both offline versions will be created manually as part of the release process by a technical writer and added to GitHub.
Change to the glossary page fixes an issue with linking within the PDF.the TOC on the title page shows 2 levels, which makes the PDF simpler to navigate.
QA: Checked that "Offline Version" link in footer would link to `/releases/` if dev version of docs, otherwise to the release version. Checked rendered output in browser. Ran linkcheck.
This commit addresses FFTK-1785 …
=> Add offline documentation

source/_static/theme_overrides.css, source/conf.py
Applied theme changes that are configurable without modifying CSS or HTML. Deeper changes to the theme can always be investigated later.
Changes of note:
* "+" symbol in sidebar next to sections which can be expanded to show subsections. We may wish to investigate changing the color to increase visibility, if this is an option we want to add to the docs.
* Background color of sidebar updated to match website
* External links are styled, so as to indicate such.
QA steps: viewed rendered html in browser, ran linkcheck.
No associated issue, minor changes to test out.
If effecting …
=> Apply new RTD theme options

source/reference-manual/security/boot-software-updates-imx8qm.rst, source/reference-manual/security/factory-keys.rst
Remove `FIT_NODE_SEPARATOR` which is deprecated in https://github.com/foundriesio/meta-lmp/pull/1504
Remove v83 warning message as it's too old
=> Some fixup

source/reference-manual/security/factory-keys.rst
The conf/keys certificates is not used anymore (and not supposed to be used), so it is removed from every factory with this commit https://github.com/foundriesio/partner-setup/commit/74d7d3fe0c2a3fea189cf2e23ce0f18ee9cb6814
However, it is already present in the fresh new factories, as every factory copies from public lmp-manifest (which includes the conf/keys) and only when the first target is built that directory is removed.
It means, while the factory only has the First Fast Target, the conf/keys is there!
The conf/keys directory from lmp-manifest should not be removed (as they are needed when building LmP without a factory)
Please let me know if you prefer to see the content of directories tf-a and uefi.
=> RM: security: Remove the dev certificate references

source/reference-manual/ota/aktualizr-lite.rst, source/user-guide/custom-sota-client.rst
CLI documentation update for v95.
---
=> ug: Add documentation for aktualizr-lite command line interface

source/user-guide/custom-sota-client.rst
A few fixes that I've missed from PR #734.
---
=> ug: Minor fixes in aklite CLI documentation

source/reference-manual/remote-access/wireguard.rst
Added to ``apt`` command to install dependencies.
QA Steps: Checked that the package name is correct, checked rendered output. Ran linkcheck. No issues found.
This commit addresses FFTK-3454, "Documentation: Wireguard dependency"
Adds missing dependency as reported by customer
=> Add iptables to wireguard dependencies

source/reference-manual/security/secure-boot-uefi.rst
When using QEMU to do UEFI PXE provisioning, declaring the boot order is necessary when booting the Secure Image.
This avoids entering the UEFI Shell.
With this commit we hope to avoid CS questions on the matter.
=> rm: security: add UEFI PXE provisioning clarification

source/reference-manual/boards/boards.rst
Link added to supported boards page.
Built html, checked that link showed and functioned as intended, No issues found.
This commit addresses FFTK-3472 "RB3G2: link to flashing instructions"
Keeping it simple; shows up in TOC for board flashing instructions, links to our external flashing instructions. This will make it easy if the instructions are ever added directly to the docs.
=> Add link to rgb3gen2 flashing instructions

source/user-guide/el2g.rst
This is not supported since Oct 1st 2024.
=> ug: el2g: add warning about deprecation

source/reference-manual/security/secure-boot-uefi.rst
Follow up to Slack discussion, the file the variables `UEFI_SIGN_ENABLE` `and UEFI_SIGN_KEYDIR` are set in was mentioned, as well as an admonition mentioning the case where this is not required.
QA steps: ran build and checked rendered HTML, ran linter. No issues found.
No related ticket, quick fix.
Let me know if I need to change anything, such as the file, or any unclear wording in the admonition.
=> Add where to set uefi variables

source/reference-manual/security/device-gateway.rst, source/user-guide/device-gateway-pki/device-gateway-pki.rst
This is an overhaul of two PKI related pages which are outdated for a long time already.
I added a lot of context to the Reference Manual, so that the user can now find all necessary information about PKI in one place.
Because of the above, quite some content was removed from the User Guide page about Factory PKI.
Instead, I improved on the original idea of that page to give more insights about how the PKI API works.
With these additions, we may now reference this updated User Guide to our users who want to integrate with the API directly.
=> Update Factory PKI docs according to recent changes

source/reference-manual/security/device-gateway.rst, source/user-guide/device-gateway-pki/device-gateway-pki.rst
References and external links fixed to use correct syntax. Also minor grammar fix on a line containing one of the broken links.
No related tickets, quick fix.
QA: ran linkcheck and viewed rendered html.
=> Fix hyperlinks from pr-699

source/reference-manual/security/device-gateway.rst, source/user-guide/device-gateway-pki/device-gateway-pki.rst
Applied fixes to grammar/style.
Ran linkcheck and linter, and viewed rendered HTML in browser.
No related ticket, quick fix
Applied changes suggested by @mike-scott, as well as a few other grammar/style changes.
Added some links to the glossary.
=> Apply cleanup to changes introduced in pr 699

source/user-guide/custom-ci/custom-ci-for-apps.rst
Replace references to `compose-publish` utility with references to `composectl publish` utility since we moved all App related functionality into the single component `composectl` and will be doing further development only in the scope of `composeapp` project.
=> ug: custom-ci: Switch to usage of the new compose publish utility

source/user-guide/foundriesio-rest-api/foundriesio-rest-api.rst
Focus was on changing the api link so that customers not logged in would see a notice of such rather than a page error. An admonition to this effect was added.
All links to the api were changed as otherwise they would need individual references.
Other minor clean done.
No related ticket, quick fix.
Follows up to discussion of issue.
=> Minor cleanup to rest api page

source/user-guide/custom-sota-client.rst
Admonition added for changes from commits 4e459db and e776a48, to allow for a re-release of docs v94. Post-publishing, this commit should be reverted/changes removed.
Built HTML and viewed in browser, ran linkcheck.
This commit addresses the issue in ticket FFTK-3545, Add temp admonitions for re-release
This commit applies to ticket FFTK-3544, Re-release v94 docs…
For re-release of v94
_This could include potential …
=> Prepare docs for re-publishing of v94

source/reference-manual/linux/linux-update.rst
No, remove all the commas (from the offending line).
QA: Built HTML, ran linkcheck and linters.
No related tickets, quick fix for issue reported internally over Slack.
Typo fix
=> Remove Extra comma on linux-update page

source/reference-manual/linux/linux-disk-encryption.rst
Following https://github.com/foundriesio/meta-lmp/pull/1530, we now allow users to define their own passphrases for CI LUKS encryption.
=> rm: CI LUKS encryption

source/conf.py
NXP link in docs requires NXP account, adding link to set of links to ignore.
QA: ran clean linkcheck build, finished without error
No related tickets/issues, quick fix
=> Address linkcheck errors

source/reference-manual/security/device-network-access.rst
Note added about ipv6 not supported for cloud services/device-gateway.
QA: linter, linkcheck, and viewed rendered HTML. No issues noted.
This commit addresses FFTK-2459, "Add note that IPv6 is not supported"
Working through older issues with quick fixes.
=> Add note that IPv6 is not supported

source/reference-manual/docker/container-secrets.rst
Removed line reported to be causing issues due to no longer being required for secrets.
QA: Ran linter, linkcheck, and viewed rendered HTML.
This commit relates to FS-2820: "…Docker Build Stages Not Caching…"
=> Remove line causing docker build issues

source/user-guide/lmp-customization/linux-building.rst
Added space, link is now in the generated HTML as intended.
QA: checked rendered output and link. Ran linkcheck. No reason to run linter.
This commit addresses FS-2843, re: fix see:ref:ref-linux-supported
=> Fix broken ref to board machine names page

source/user-guide/account-management/team-based-access.rst
The documentation was reworded. The changes should help clarify that members with read-only permission can still view other groups and devices.
QA: Viewed rendered html, edited with linter plugin. Ran linkcheck.
This commit addresses ticket FFTK-3602, "clarify device group read permission details"
Addresses point of confusion for customer
=> Clarify device group read-only permission

source/tutorials/customizing-the-platform/commit-and-push-recipe.rst
Note added to the tutorial.
QA: Ran linter, and checked rendered output in browser.
This commit addresses task FFTK-1895,"…CI and `meta-subscriber-overrides` commit usage"
Older task from backlog to add documentation regarding CI and `meta-subscriber-overrides ` commit usage.
Linkcheck only produced expected errors.
=> Add note regarding CI and meta-subscriber-override

source/reference-manual/linux/linux-update.rst, source/user-guide/troubleshooting/troubleshooting.rst
=> Customer facing improvements

source/user-guide/fioctl/index.rst
Added links and reworked page summary for Fioctl.
QA Steps: viewed HTML in browser and ran linter.
Linter warnings can be ignored.
Only expected inkcheck errors found.
This commit addresses Jira FFTK-990, "Improve intro to fioctl"
=> Improve introduction of fioctl guide

source/reference-manual/ota/aktualizr-lite.rst, source/reference-manual/ota/fioconfig.rst
Tested by building the HTML docs.
Fixes a couple of trivial typos
I tried to see why vale didn't catch these; I tried enabling other packages such as Google and Microsoft, but while that provided useful new suggestions, it still didn't catch the typos. When I set Vale.Spelling to YES in .vale.ini, it did catch the typos, but it also reported a ton of other errors even for words in accept.txt.
=> Fix a couple of trivial typos

source/tutorials/compose-app/compose-app-docker-compose-apps.rst
Update the tutorial on Compose Apps with an info about the limit on size of the compose app bundle (effectively the app directory).
=> tutorial: add info about app bundle size limit

source/getting-started/install-fioctl/index.rst, source/user-guide/troubleshooting/troubleshooting.rst
Removed `sudo` for setting up Git with Fioctl.
May require further modifications.
Additionally, some changes made to further clean up the edited pages.
QA: Checked rendered output in browser.
This commit addresses issue FFTK-3728, "document changes to git cred..."
Linkcheck and linter errors reviewed and acknowledged, can be ignored.
=> Document changes to fioctl git credential helper

source/_static/csv/supported-boards.csv, source/reference-manual/security/imx-generic-custom-keys.rst, source/reference-manual/security/secure-boot-imx-habv4.rst
Removed mentions and from supported board list. No dedicated page, so no redirects added.
QA: built docs, ran linkcheck. Edited with linter on.
This commit addresses issue FFTK-3725, "Remove i.MX7ULP"
=> Remove imx7ulp support

source/user-guide/custom-ci/custom-ci-for-rootfs.rst, source/user-guide/custom-sota-client.rst
Update aktualizr-lite CLI information considering improvements made for v95
=> Aklite v95 changes

.vale.ini
Updating to Fio-docs 2.5.0 which has a couple additions to check for.
QA: checked that vale sync worked and was able to fetch the package.
No associated issue, minor maintenance task.
=> Update linter style rules version

source/_templates/layout.html
Changed to properly use roboto-flex.
QA: checked output in browser, used browser tools to verify font use.
This commit addresses issue FFTK-2123, "Update font"
=> Fix change to font

source/tutorials/creating-first-target/what-is-a-target.rst
Admonition expanded with additional info.
QA: checked rendered output, edited with linter.
This commit addresses FFTK-1703, "Define what a Target is not"
=> Add what a Target is not to tutorial

source/reference-manual/linux/linux-kernel.rst
Ran through release notes draft for v95 to check for missed doc changes. Only one change was missed, which relates to the now deprecated support for the xenomai4 kernel feature.
QA: checked for references to deleted section, none found.
This commit applies to issue FFTK-3230, "Review…"
=> Review docs for missed changes

release-notes/rn_v95.md, source/index.rst, source/user-guide/custom-sota-client.rst, source/user-guide/troubleshooting/troubleshooting.rst
RN: Add the initial version for the v95 Release Notes
missing: 
- Link for the test results
- [FAQ](https://docs.foundries.io/latest/user-guide/troubleshooting/troubleshooting.html#jailhousesupportin-lmp-is-removed)
- [FAQ](https://docs.foundries.io/latest/user-guide/troubleshooting/troubleshooting.html#update-foundriesfactory-fanifest-merge-conflict)
=> release-notes: add release notes for the v95 release

release-notes/rn_v95.md
=> release notes: v95: fix typo

source/tutorials/compose-app/compose-app-commit-push-all-new-apps.rst, source/tutorials/compose-app/compose-app-docker-compose-apps.rst, source/tutorials/compose-app/compose-app-testing-applications.rst, source/tutorials/customizing-the-platform/commit-and-push-recipe.rst, source/tutorials/getting-started-with-docker/extra-commands.rst, source/tutorials/working-with-tags/adapting-shellhttpd.rst, source/tutorials/working-with-tags/creating-targets.rst, source/tutorials/working-with-tags/following-specific-tag.rst, source/tutorials/working-with-tags/inspecting-targets.rst, source/tutorials/working-with-tags/working-with-tags.rst
Customer feedback and additional cleanup applied to tutorials.
QA: ran vale linter while editing, checked rendered HTML output.
This commit addresses issue FFTK-1460, "fixes based on…conversations"
=> Apply feedback on tutorials

source/reference-manual/security/secure-elements/se050-enablement.rst
Section was marked from removal, as the info is unlikely to be relevant now.
QA: ran build and checked rendered ouput
No related issue, quick fix.
=> Remove special cases from enabling se05x

source/user-guide/lmp-customization/linux-building.rst
Building with a Factory was moved ahead of building without. Other minor changes made to page.
QA: Viewed rendered output, and edited with linter rules checked with an extension. No Issues.
No related issue, minor fix following up on internal Slack discussion.
=> Reorder linux building guide

source/_static/csv/supported-boards.csv, source/getting-started/flash-device/index.rst, source/reference-manual/ota/device-tags.rst, source/reference-manual/ota/targets.rst, source/reference-manual/testing/fiotest.rst, source/tutorials/configuring-and-sharing-volumes/copy-configuration-file-using-dockerfile.rst, source/tutorials/configuring-and-sharing-volumes/dynamic-configuration-file.rst, source/tutorials/creating-first-target/what-is-a-target.rst, source/tutorials/deploying-first-app/debugging-your-device.rst, source/tutorials/working-with-tags/adapting-shellhttpd.rst, source/tutorials/working-with-tags/following-specific-tag.rst, source/tutorials/working-with-tags/inspecting-targets.rst, source/tutorials/working-with-tags/tagging-specific-version.rst, source/user-guide/containers-and-docker/compose-apps.rst, source/user-guide/fioctl/index.rst, source/user-guide/foundriesio-rest-api/foundriesio-rest-api.rst, source/user-guide/lmp-auto-hostname/lmp-auto-hostname.rst
Removed from supported-boards CSV.
In most instances, references were updated to "raspberry pi 4". Additional changes were made in some files to address minor issues that were spotted.
Ran build, no issues, output not checked due to the number of files, and the simplicity of the changes.
This commit addresses issue FFTK-4105, "deprecate raspberrypi3 64…"
Removes/replaces rpi3 in the docs
=> Remove rpi3 from documentation

source/user-guide/developer-workflow/developer-workflow.rst, source/user-guide/index.rst, source/user-guide/waves/waves.rst
This covers common workflows and information we share with customers during Onboarding.
This aims to reduce the entry bar to start developing with FoundriesFactory.
=> ug: introduce Developer Workflow and Guidelines page

source/getting-started/register-device/index.rst
Previously, our "fast first target" artifacts were built from the "main" branch of the LmP and would auto-register using the "main" tag.
With the latest changes to our LmP workflow, we now have LTS branch names such as "scarthgap" and also a "main" branch representing upstream Yocto / OE development.
The artifacts used for LmP version releases will most likely come from an LTS branch, and will attempt to register using that branch name by default (IE: "scarthgap" tag).
The device should be registered to follow the "main" tag to match the 2nd target of a newly created Factory.  So let's add the "-t main" parameter to our docs.
All PRs should be reviewed by a …
=> getting-started: register-device: add tag parameter for first target
