foundriesio/docs

.jobserv.yml, extensions/core.py, extensions/rpi3.py, source/conf.py, source/reference/linux-targets.rst, source/tutorial/installation-linux.rst
These are now uploaded to GitHub for anyone to use.
=> LMP: Update location of LMP binary artifacts

source/tutorial/installation-zephyr.rst
Signed-off-by: Marti Bolivar <marti@foundries.io>
=> installation-zephyr: fix macos and windows west installation

source/reference/linux-ota.rst, source/reference/linux-targets.rst, source/tutorial/installation-linux.rst, source/tutorial/iot-gateway-setup-common.include
=> move from osf to fio for login information

source/reference/linux-building.rst
=> linux-building: update build instructions to use ubuntu 18.04

source/customer-factory/index.rst
=> customer-factory: add note about subscription

source/community-factory/create-factory.rst, source/community-factory/index.rst, source/index.rst
Add a brief section about the benefits of creating your own factory.
=> FF-76: add section about creating a factory

source/reference/aktualizr-lite.rst, source/reference/linux.rst
Basic usage guide for aktualizr-lite.
=> advanced topics: add ak-lite usage page

source/reference/docker-apps.rst
=> ref: docker-apps: add instructions for manual update

source/customer-factory/containers.rst, source/customer-factory/managing.rst
=> containers: add note for lmp-device-register

source/community-factory/docker-apps.rst, source/customer-factory/containers.rst, source/customer-factory/updating-the-core.rst, source/reference/docker-apps.rst
Update the container sections to clarify feedback from users.
=> WIP: Container documentation updates

source/community-factory/index.rst, source/customer-factory/docker-apps.rst, source/customer-factory/getting-started.rst, source/customer-factory/index.rst, source/customer-factory/managing.rst
=> Docker-apps: Updates requested by George

source/community-factory/docker-apps-k3s.rst, source/community-factory/docker-apps.rst
first rst file I've written I believe, so get your eagle eyes out @MiloCasagrande @doanac
=> added detail about k3s app

source/reference/linux.rst, source/reference/secure-boot.rst
=> secure-boot: document the secure boot sequence for i.MX7ULP

source/reference/advanced-tagging.rst, source/reference/linux.rst
As factories and CI stories get more complex, we are finding the need
to introduce more powerful ways to do handle tagging. This change
adds a new document to help explain what's possible. Its based
on the issue defined here:
https://github.com/foundriesio/ci-scripts/issues/44
=> reference: Add "Advanced Tagging" section

source/_templates/layout.html
Update our GA code using a reference from https://www.sphinx-doc.org/en/master/faq.html 
=> templates/layout: ga do not use script src

source/reference/linux-targets.rst
=> linux-targets: add instructions for imx8mmevk

source/reference/secure-boot.rst
- We now use sign-file.sh which greatly simplifies signing process
- Add instructions for signing M4 binary
=> secure-boot: update secure signing instructions

source/customer-factory/docker-apps.rst, source/customer-factory/extending.rst, source/customer-factory/source-code.rst, source/customer-factory/updating-the-core.rst
=> customer-factory: replace partners for factories

source/reference/secure-boot.rst
Some projects might define a close.uuu script in their
meta-subscriber-overrride to perform further verification before
closing the device. It is unlikely that such a script will be
executing a signed SPL and therefore will not succeed as HAB events
will be triggering on boot.
This commit raises the awareness of the need to update all of the users UUU
scripts once the fuses have been burnt (before even closing the device).
=> secure-boot: clarify the need to update the UUU scripts after fusing

.gitignore, source/reference/container-secrets.rst
updates to the fioctl command documented here
=> added secret removal documentation

source/conf.py
=> updated copyright dates

source/reference/aktualizr-lite.rst
=> fixed documentation copy pasta bug

source/reference/secure-boot.rst
=> secure boot: clarify need to clear dcd on SDP boot

source/customer-factory/updating-the-core.rst
- moved the script to lmp-tools so include that in the instructions.
=> updating-the-core: fixup update-factory-manifest instructions

source/reference/linux.rst, source/reference/vpn.rst
=> Add wireguard vpn section

source/reference/device-testing.rst, source/reference/linux.rst
=> Add device testing reference

requirements.txt, source/conf.py
Add emoji support in preparation for opportunistic :cowboy_hat_face: insertion.
https://sphinxemojicodes.readthedocs.io/en/stable/#supported-codes
=> Add and enable sphinxemoji plugin

source/getting-started/git-config/index.rst, source/index.rst
Some sections are still yet to be added, this is noted in the todo directive. Fixes #64
=> getting-started: git configuration

source/reference/app-conversion.rst
=> app-conversion: Fix bugs

source/reference/vpn.rst
=> wireguard: Start some troubleshooting notes

source/reference/linux.rst, source/reference/secure-element.050.rst
Succinct documentation about the NXP SE050
=> secure-element: introduction to the NXP SE050

source/tutorials/aws.rst, source/tutorials/google.rst, source/tutorials/ibm.rst, source/tutorials/mosquitto.rst
I'm taking a look at the tutorials and am currently going through them to check for validity, so I'm going to be submitting PRs during the week, this is the first. 
*Note* needs to be merged to refactor after successful merge into master.
=> Fix extra-containers reference and some typos

source/getting-started/git-config/index.rst, source/getting-started/signup/index.rst
=> Refactor improvements 1

.jobserv.yml, requirements.txt
`sphinx` and `sphinx-tabs` have updated in the meantime.
=> requirements: update requirements.txt

source/getting-started/create-compose-app/index.rst, source/getting-started/flash-device/index.rst, source/getting-started/git-config/index.rst, source/getting-started/install-fioctl/index.rst, source/getting-started/register-device/index.rst, source/getting-started/signup/index.rst
Removes emojis from the getting-started titles.
=> getting-started: remove all emojis

source/tutorials/mosquitto.rst
Mosquitto Tutorial was broken because the files from extra-container weren't accepted on the pull request.
I updated the extra container and sent a new pull request there as well.
=> mosquitto: Adding some updates and corrections

source/_static/css/og.css, source/conf.py, source/index.rst
Add a link to the FoundriesFactory dashboard in the ToC, and make the "corporate" links stand out a little bit more.
=> Add link to dashboard

source/reference/containers.rst
As per:
https://github.com/foundriesio/ci-scripts/commit/0039b6e3ca04b31295ecf7c5fa44c0fb9354a087
=> containers: Add information about `pre-build.conf`

source/tutorials/mosquitto.rst
After Mike Sul review, he suggested those improvements implemented in this commit.
=> mosquitto: correcting some errors and improving text

source/reference-manual/ota/aktualizr-lite.rst
=> aktualizr-lite: Add doc on aklite conf params

.jobserv.yml, source/conf.py, source/getting-started/create-compose-app/index.rst, source/getting-started/flash-device/index.rst, source/getting-started/git-config/index.rst, source/getting-started/install-fioctl/index.rst, source/getting-started/signup/index.rst
follow up from #103 
Commit messages should be self explanatory as a changelog.
=> Refactor improvements 2

.jobserv.yml
=> jobserv: Docs building now needs amd64

source/reference-manual/docker/containers.rst
=> docker: Add documentation for build args

source/reference-manual/docker/docker-architecture.rst, source/reference-manual/docker/docker.rst
=> docker: Add an architecture overview

source/reference-manual/factory/api-access.rst, source/reference-manual/factory/factory.rst
=> Add technical details of api tokens

source/reference-manual/linux/linux-layers.rst
=> reference-manual: linux-layers: add initial description for meta-lmp-bsp

source/reference-manual/linux/linux-wic-installer.rst
=> reference-manual: linux-wic-installer: add qemu usage instructions

source/user-guide/configure-lmp/index.rst
=> user-guide::configure-lmp better page layout for recipes

source/_static/csv/supported-boards.csv
=> Add imx8mqevk to the supported boards list

source/user-guide/configure-lmp/index.rst
=> Improvements 04

source/reference-manual/security/secure-boot-imx.rst
=> Change where to find the sign-file.sh script

README.md
Add steps needed for building documentation locally.
=> README.md: add steps for building docs

source/reference-manual/boards/beagleboneblack.rst, source/reference-manual/boards/boards.rst
=> boards: add flashing instructions for Beaglebone Black

source/reference-manual/linux/linux-kernel.rst
=> linux-kernel: add instructions for real-time linux

source/getting-started/install-fioctl/index.rst
=> getting-started: Suggest the installation of Curl before fioctl install

source/getting-started/signup/index.rst, source/reference-manual/docker/compose-apps.rst, source/reference-manual/factory/factory-definition.rst
=> getting-started::reference-manual:: Fix typos

source/reference-manual/qemu/arm64-substitutions.inc, source/reference-manual/qemu/qemu-instructions.template, source/reference-manual/qemu/riscv64-substitutions.inc, source/reference-manual/qemu/riscv64.rst, source/reference-manual/qemu/x86_64-substitutions.inc
- Adds instructions for booting QEMU graphically
- Warns about minimum required QEMU version
- Links to status of riscv64 pci-e/gpu support in qemu
=> Add QEMU GUI Instructions

source/reference-manual/linux/linux-extending.rst, source/reference-manual/linux/linux-net-debug.rst, source/reference-manual/linux/linux-persistent-log.rst, source/reference-manual/linux/linux-wic-installer.rst, source/reference-manual/ota/advanced-tagging.rst, source/reference-manual/ota/device-tags.rst, source/reference-manual/qemu/arm64.rst, source/reference-manual/qemu/qemu-instructions.template
reference-manual::qemu Fix QEMU arm64 command line
reference-manual::qemu Add instructions to set needed environment variable
reference-manual:: Fix typos
=> General fixes in docs

source/reference-manual/security/device-gateway.rst, source/reference-manual/security/offline-keys.rst, source/reference-manual/security/secure-boot-imx.rst
=> reference-manual::security:: Fix typos

CONTRIBUTING.md
Adds a CONTRIBUTING.md which highlights some of the practices I've seen @vanmaegima begin to implement, this will grow over time.
=> github: init CONTRIBUTING.md #175

source/getting-started/signup/index.rst
After some work, we have optimized the first build and the build
time is much faster now.
=> updating message after creating new a Factory.

source/getting-started/git-config/index.rst, source/getting-started/install-fioctl/index.rst
=> getting-started:: Add information on token scopes for new user

source/getting-started/create-compose-app/index.rst, source/getting-started/git-config/index.rst, source/getting-started/install-fioctl/index.rst, source/getting-started/signup/index.rst
getting-started:: Add information on token scopes for new user
getting-started:: Add information to illustrate the first update process
getting-started:: Add information on Targets
=> getting-started:: General improvements for new users

source/conf.py
=> conf: update copyright

source/reference-manual/security/secure-boot-imx.rst
Add details about fusing steps for i.MX8MM SoC.
=> security: secure-boot-imx: add fusing details for i.MX8MM

source/reference-manual/boards/imx8-prepare.rst
Update flash instructions for i.MX 8M Mini EVK.
=> boards: imx8mm: update flash instructions

source/getting-started/create-compose-app/index.rst, source/getting-started/flash-device/index.rst, source/getting-started/install-fioctl/index.rst, source/getting-started/register-device/index.rst, source/reference-manual/boards/imx6-flashing.rst, source/reference-manual/boards/imx8-flashing.rst, source/reference-manual/factory/factory-definition.rst, source/reference-manual/qemu/arm-substitutions.inc, source/reference-manual/qemu/arm64-substitutions.inc, source/reference-manual/qemu/qemu-instructions.template, source/reference-manual/qemu/x86_64-substitutions.inc, source/reference-manual/remote-access/wireguard.rst, source/reference-manual/troubleshooting/troubleshooting.rst, source/tutorials/aws.rst, source/tutorials/google.rst, source/tutorials/ibm.rst, source/user-guide/configure-lmp/index.rst, source/user-guide/fioctl/index.rst
=> doc: delete all occurrence of trailing whitespaces/tabs

README.md, requirements.txt, source/conf.py
Sphinx directive to add unselectable prompt
=> sphinx-prompt: add package

source/reference-manual/security/offline-keys.rst
This is updated to go into a little more detail about key rotation
and also introduce the new offline target key customers need to create.
There were a lot of "notes" that were a little distracting.
Additionally, one was no longer accurate and one was slightly
inaccurate.
=> security: Update the offline signing doc

source/reference-manual/ota/ota.rst, source/reference-manual/ota/production-targets.rst
=> Add a production targets section

source/reference-manual/factory/fioctl/fioctl.rst, source/reference-manual/linux/linux.rst, source/reference-manual/linux/preloaded-images.rst
=> Add documentation about preloaded images

source/getting-started/create-compose-app/index.rst, source/getting-started/flash-device/index.rst, source/getting-started/git-config/index.rst, source/getting-started/install-fioctl/index.rst, source/getting-started/register-device/index.rst
- Changed all code blocks to prompt to help customers understand when
it is a host command and when it is a device command.
=> getting-started: update code block to prompt

source/reference-manual/ota/ota.rst, source/reference-manual/ota/production-targets.rst, source/reference-manual/ota/static-deltas.rst
=> reference: Add documentation for static deltas

source/reference-manual/linux/linux-oss-compliance.rst, source/reference-manual/linux/linux.rst
=> Add a section on OSS compliance

source/reference-manual/docker/compose-apps.rst
=> compose-apps: Add link to information about composeappignores

source/reference-manual/linux/preloaded-images.rst
Trying to put a little more content about scenarios that have been popping up lately.
=> Preload updates

source/tutorials/deploying-first-app/enabling-specific-applications.rst
On the command:
fioctl devices config updates --compose-apps --apps
--compose-apps is an unknown flag
=> tutorials: Update cmd

source/conf.py, source/reference-manual/factory/ci-webhooks.rst, source/reference-manual/factory/factory-definition.rst, source/reference-manual/factory/factory.rst
=> Add reference documentation for webhooks

source/reference-manual/linux/linux-distro.rst, source/reference-manual/linux/linux.rst
=> rm: linux: Describe the LmP Distros

source/reference-manual/security/device-gateway.rst
=> reference-manual: security: guide on the PKI API

source/reference-manual/linux/development-tags.rst, source/reference-manual/linux/linux.rst
=> rm: linux: add section on development FIO tags

source/reference-manual/linux/linux-distro.rst
=> rm: linux: Include code sample on how to setup DISTRO

source/reference-manual/factory/factory-sources.rst
=> rm: factory: Add ci-scripts notes

source/tutorials/compose-app/compose-app.rst, source/tutorials/working-with-tags/working-with-tags.rst
=> tutorials: Updating estimated time

source/reference-manual/troubleshooting/troubleshooting.rst
A set of information helpful for subscribers.
=> FAQ improvements

source/_static/csv/supported-boards.csv, source/reference-manual/security/secure-machines.rst
=> rm: security: secure-machines: add imx8mm-lpddr4-evk-sec

source/reference-manual/factory/factory-keys.rst, source/reference-manual/factory/factory.rst
=> rm: factory: Add how to rotate the LmP keys from the factory

source/reference-manual/boards/apalis-imx6.rst, source/reference-manual/boards/imx6ull.rst, source/reference-manual/boards/imx8mm.rst, source/reference-manual/boards/secure-boot-note.rst, source/reference-manual/boards/secure-boot-pre-flash-note.rst
=> rm: boards: Add notes to help with secure boot

source/user-guide/container-preloading/container-preloading.rst
=> container-preloading: review minor grammar fixes

source/reference-manual/factory/factory-definition.rst
=> factory-definition: update preloaded

source/reference-manual/linux/preloaded-images.rst
=> reference-manual: preloaded-image: update

source/reference-manual/factory/factory-keys.rst
=> rm: factory-keys: Add version when factory-key dir were created

source/reference-manual/security/authentication-xilinx.rst
Extend description to support building pmu/spl and the final image using
lmp.
=> authentication-xilinx: extend to support building via lmp

source/reference-manual/security/authentication-xilinx.rst
=> authentication-xilinx: add instructions about registering the PUF

source/reference-manual/docker/docker.rst, source/reference-manual/docker/restorable-apps.rst, source/reference-manual/linux/linux-distro.rst, source/user-guide/container-preloading/container-preloading.rst
=> Guide on Restorable Apps

source/reference-manual/security/security.rst
=> security: Add a security overview

source/reference-manual/security/security.rst
=> security: extend overview to cover secure boot

source/reference-manual/docker/private-registries.rst
=> containers: Add info for Azure Container Registry

source/_static/csv/revoke_imx.csv, source/reference-manual/security/revoke-imx-keys.rst, source/reference-manual/security/secure-boot.rst
=> security: Add how to revoke a key for imx

source/tutorials/compose-app/compose-app-flask-mqtt-nginx.rst
Signed-off-by: Eric Bode <eric.bode@foundries.io>
=> compose-app: changed dependences into dependencies

source/reference-manual/docker/private-registries.rst
Include some details about how to handle device authentication with ECR
=> docker: Update 3rd party registry info for ECR

source/reference-manual/security/secure-elements/secure-element.050.rst
=> Fix broken link

source/reference-manual/troubleshooting/troubleshooting.rst
=> rm: troubleshoot: faq: add steps to set a static ip for the board

source/reference-manual/troubleshooting/troubleshooting.rst
Made edits to troublshooting.rst, fixing a change introduced in PR #307.
"Fixed" a issue with the enumeration in the same document, which also
seemed to be introduced at the same time
=> Fix syntax errors from previous merge

source/reference-manual/docker/containers.rst
This comes up every now and again
=> docker: Add another pre-build.conf example

source/reference-manual/ota/aktualizr-lite.rst
=> rm: Add info on the "storage_watermark" param of aklite

source/reference-manual/ota/aktualizr-lite.rst, source/reference-manual/ota/ota.rst, source/reference-manual/ota/update-rollback.rst
=> rm: Add doc on Update Rollback

source/reference-manual/troubleshooting/troubleshooting.rst
=> rm: troubleshooting: add how to automatically load a kernel module

source/reference-manual/troubleshooting/troubleshooting.rst
=> rm: troubleshooting: minor fixes

source/reference-manual/factory/api-access.rst
=> rm: Update API access methods

source/_static/push_queue_example.py, source/reference-manual/factory/event-queues.rst, source/reference-manual/factory/factory.rst
=> rm: Add documentation for event queues

source/reference-manual/docker/private-registries.rst, source/reference-manual/factory/factory-definition.rst
=> rm: Add details for Google Artifact Registry

source/getting-started/git-config/index.rst
Added links mentioned in the todo notes on the page, minor changes made
such as word use and phrasing.
QA steps taken: read through documented, ran spellcheck and linkcheck,
built html and examined rendered content. No changes made to examples,
so the steps were not walked through.
This applies to FFTK 988.
=> Cleanup getting started:git config page

source/reference-manual/troubleshooting/troubleshooting.rst, source/tutorials/configuring-and-sharing-volumes/sharing-folder.rst
Added two notes, on in the sharing folder tutorial, and
a entry under troubleshooting.
QA steps taken: ran linkcheck and build locally, viewed changes in
browser.
This commit addresses Jira FFTK #1404.
=> Add admonition to bind mount a files parent dir

LICENSE
CC Attribution 4.0 International added and place in the License file.
This commit will close issue #369 (1504 in Jira)
=> Add License to docs

source/reference-manual/factory/factory-keys.rst
Added a minimal amount of info on spldev support. Decided against having
an admonition pointing out that there are two u-boot keys, which is
dependent on hardware features, to keep it short. Open to adding more
info if we think it is needed. There is cleanup tasks to be done
regarding word choice and grammar, but that will be in a following
PR.
Rendered page locally, and ran Vale linter. No *new* issues reported.
This addresses Jira FFTK-1597.
I am open to adding additional changes, kept it fairly minimal.
=> Add spldev key to RM:factory:factory-keys page

source/user-guide/container-preloading/container-preloading.rst
Extend the doc about preloading Apps with an info about an OE-builtin preloading (new feature).
=> ug: cp: Add doc on OE-builtin preloading

source/reference-manual/factory/factory-sources.rst, source/reference-manual/troubleshooting/troubleshooting.rst
General fixes to improve the docs and some feedback from customers.
=> Non-critical fixes

source/reference-manual/testing/lmp-testplan.rst, source/reference-manual/testing/testing.rst
=> reference-manual: add test plan

source/reference-manual/security/secure-boot-uefi.rst
This solves build issues with customer generated keys
=> security: added files needed for secure boot uefi builds

source/reference-manual/docker/container-secrets.rst, source/tutorials/working-with-tags/adapting-shellhttpd.rst, source/tutorials/working-with-tags/creating-targets.rst
Changes from customer feedback.
=> Identation fix

source/reference-manual/security/device-network-access.rst, source/reference-manual/security/ota-security.rst
This is a common customer question that we should be able to easily link to.
=> rm: Add document about outbound network needs

.gitignore, .vale.ini, CONTRIBUTING.md, Makefile
Basic support for running the vale documentation linter added.
Configuration for what styles are used can be changed by editing
`.vale.ini` and editing the `BasedOnStyle` variable. Options to
use lint using make was added as well.
Quick checks were performed to test for expected results, however this
was far from exhaustive.
This commit addresses FFTK #1630
Added a configuration file for the vale linter.
If vale is installed, running `vale sync` will pull the latest release package from the `fio-style` repo which will include additional styles that can be used.
Also added was two options for make, `make lint-all` and `make lint-diff`. …
=> Add support for linter

source/index.rst, source/reference-manual/security/device-gateway.rst, source/user-guide/device-gateway-pki/device-gateway-pki.rst
Signed-off-by: Mike <mike.sul@foundries.io>
=> ug: dg: Move PKI setting details from rf to ug

source/reference-manual/factory/data-retention.rst, source/reference-manual/factory/factory.rst
=> rm: Add a data retention policy doc

source/index.rst, source/reference-manual/factory/data-retention.rst, source/reference-manual/factory/factory.rst, source/reference-manual/security/device-gateway.rst, source/user-guide/device-gateway-pki/device-gateway-pki.rst
=> prepare for default branch switch

source/reference-manual/remote-access/wireguard.rst
Many customers have had problems setting up servers.
* [x ] Avoid changing any header associated with a link/reference.
* [x ] Step through instructions (or ask someone to do so).
* [x ] Review for [wordiness](https://languagetool.org/insights/post/wordiness/)
* [x ] Match tone and style of page/section.
=> docs: update troubleshooting in wireguard section

source/reference-manual/factory/event-queues.rst, source/tutorials/compose-app/compose-app-checking-app-state.rst, source/tutorials/compose-app/compose-app.rst
Signed-off-by: Mike <mike.sul@foundries.io>
=> compose-app: Add tutorial about checking App states

source/index.rst, source/user-guide/el2g.rst
We are delivering a new feature in our next LmP release. We still need to work out some of the cross-company documentation and wording, but I'd like to get some early feedback on the actual instructions I've got. Could you please help me clean this up some so that I can share it?
=> Add el2g integration documentation

source/reference-manual/security/secure-elements/se050-enablement.rst
=> rm: security: se05x: change optee version note to >= 3.15.0

source/reference-manual/linux/linux-layers.rst
=> Update meta-lmp layers references and links

source/reference-manual/security/boot-software-updates-zynqmp.rst
Improve details about usage of multi_boot U-Boot cmd.
=> rm: security: improve boot software updates article for zynqmp

source/reference-manual/boards/imx8-flashing.rst, source/reference-manual/linux/linux-persistent-log.rst, source/reference-manual/ota/production-targets.rst, source/reference-manual/troubleshooting/troubleshooting.rst
Covering some customer feedback and Jira issues
=> General Improvements

requirements.txt, source/conf.py, source/index.rst, source/reference-manual/factory/factory.rst, source/user-guide/account-management/account-management.rst, source/user-guide/account-management/team-based-access.rst
Moved the file from the `reference-manual/factory/` dir to `user-guide/account-management/team-based-access`. A index page for the new location was added, and the one for the reference manual was update.
To handle any potential links to
`.../latest/reference-manual/factory/team-based-access.html`, a redirect was added, which required a Sphinx extension be added.
QA Steps: Tested the redirect locally with no issues, and checked the rendering of the page, also without issues. It is possible that the extension may need to have a version specified to build via the CI, so the PR will also serve as part of the QA Steps.
This relates to Jira FFTK 1781
This is one of a series meant to reorganize information between the Reference Manual …
=> Move team based access to new UG section

source/reference-manual/security/secure-elements/se050-enablement.rst
Add stm32mp15-disco to the list of the supported machines.
=> rm: security: se050: add details about stm32mp15-disco

source/reference-manual/docker/containers.rst, source/reference-manual/troubleshooting/troubleshooting.rst
Important information based on customer interactions.
=> Improvements based on customer interaction

source/reference-manual/linux/linux-wic-installer.rst
=> Minor fixes for the lmp installer qemu instructions

source/_static/csv/supported-boards.csv
=> source: supported-boards: drop non supported targets

source/user-guide/el2g.rst
We now have documentation from NXP we can share
=> el2g: Include links to el2g documentation

source/reference-manual/security/boot-software-updates-stm32mp1.rst, source/reference-manual/security/boot-software-updates.rst
Add article with details about boot software updates implementation on STM32MP1 SoC.
=> rm: security: boot software updates for stm32mp1

source/reference-manual/boards/boards.rst, source/reference-manual/boards/uz3eg-iocc.rst
Add flashing steps for uz3eg-iocc board.
=> rm: boards: add flashing steps for uz3eg-iocc board

source/porting-guide/pg-spl-kernel.rst, source/reference-manual/boards/boards.rst, source/reference-manual/boards/se050_imx8mm.rst, source/reference-manual/security/offline-keys.rst, source/reference-manual/security/secure-elements/se050-enablement.rst, source/reference-manual/security/secure-machines.rst
This includes information for imx8mn, customer feedback and general improvements.
=> JIRA review

source/reference-manual/factory/factory.rst, source/reference-manual/factory/sboms.rst
Review done as a separate commit. A bit of cleanup was done, though no major changes to content required.
Rendered locally, content appeared to be as intended. Link-check failure is due to an external issue.
This relates to doc PR #419
* [] Avoid changing any header associated with a link/reference.
* [] Match tone and style of page/section.
Rather than getting permission to push to @doanac fork, pushed to a new branch of the main repo. @angolini I believe most of your comments were already addressed, but feel free to give feedback.  If all looks good, I can just copy/paste this as a review of …
=> Review new SBOM page

source/reference-manual/factory/factory-keys.rst
The goal of this PR is to reorganize this page to make it easier to be used.
=> rm: Reorganize the page for keys on a factory

source/user-guide/account-management/account-roles.rst, source/user-guide/account-management/team-based-access.rst
Information on scope, especially for devices, as well the ways that account roles effect scope.
QA steps taken was linkcheck and checking documentation rendering locally.
Also used vale linter and spellcheck.
This commit addresses Jira FS #1080
Added some additional information as requested by customers.
It was initially requested for "roles" however some information was a better fit under teams,
which deals with scope
Some details were filled in from implicit/between the lines info, so it may be good to fact check these documents.
=> Add info for Factory access and scope

source/user-guide/device-gateway-pki/device-gateway-pki.rst
Update the guide on a factory PKI to make it inline with implementation and recent findings.
=> Update pki doc hash

source/reference-manual/ota/aktualizr-lite.rst, source/reference-manual/security/secure-boot-imx-ahab.rst, source/reference-manual/security/secure-boot-imx-habv4.rst
=> Secure machine fixes + customer feedback 

CONTRIBUTING.md, templates/reference-manual.rst, templates/tutorial.rst, templates/user-guide.rst
Templates added for tutorials, user guides and reference manual pages. These can be found in `templates/`.
QA steps were not performed.
This commit applies to Jira FFTK Epic #1792
This commit applies to Jira FFTK Story #1794
This commit applies to Jira tasks #1906, #1907, #1908, #1909
Added templates.
This can be especially useful for new contributors, as well as for adding new pages.
The aim is to provide a general structure, but not "hard rules" that must be followed.
More detailed information about different section pages can be found in the style guide.
Feel free to make any suggestions, or you can make commits later — "field …
=> Add templates

source/reference-manual/linux/factory-device-reset.rst, source/reference-manual/linux/linux.rst
Describe how to revert any device changes to bring it back to 'fresh manufacturing' state.
Describe feature already present in LmP but not yet documented.
=> rm: Add device factory reset

source/reference-manual/security/secure-elements/secure-element.050.rst, source/reference-manual/troubleshooting/troubleshooting.rst
=> Secure element

source/reference-manual/security/secure-boot-imx-habv4.rst
We want the customers to walk through fusing and closing their board through the scripts we provide for each -sec machine, so point them to the other page.
=> rm: habv4 secure boot: point to the secure machines page

source/reference-manual/security/device-network-access.rst
* [ x ] Merge (pending reviews)
=> rm: include hub-auth link for device network access

source/reference-manual/factory/factory.rst, source/reference-manual/factory/sboms.rst, source/user-guide/account-management/account-management.rst
Landing page added with a brief summary of FoundriesFactory. Introductions to all the sections also listed in the page's toc was added. A "seealso" admonition was added, linking to Factory account management. Page labels were added to the page on SBOMs and for account management.
QA steps include in buffer linting and checking the html rendering.
This commit applies to Jira FFTK 1903
Landing page, first of many. Open to any suggestions. May need to be update as documentation is reorganized. 
* [] Step through instructions (or ask someone to do so).
* [] Match tone and style of page/section.
* [] Run `make linkcheck`.
We may want to …
=> Add landing page for RM:FoundriesFactory section

source/reference-manual/linux/linux-kernel.rst
I decided to duplicate the same section, however I would like to hear in case of any better idea.
=> rm: linux: Add howto for linux-lmp-fslc-imx-rt

source/reference-manual/linux/linux.rst, source/reference-manual/linux/toolchain.rst
Signed-off-by: Jose Quaresma <jose.quaresma@foundries.io>
This merge add some notes on who to use the clang toolchain.
=> rm:linux: Add how to build with the clang toolchain

source/index.rst, source/user-guide/custom-ci/custom-ci-for-apps.rst, source/user-guide/custom-ci/custom-ci-for-rootfs.rst, source/user-guide/custom-ci/custom-ci.rst
Signed-off-by: Mike <mike.sul@foundries.io>
=> ug: Add user guides on custom CI for OS and apps

source/reference-manual/linux/linux-extending.rst
For building with private keys these will generate the correct file.
* [* ] Merge (pending reviews)
* [ *] Request PR review by a technical writer and at least one peer.
=> Add how to generate a known_hosts file for CI builds

source/reference-manual/linux/preloaded-images.rst, source/user-guide/container-preloading/container-preloading.rst
We have RM and UG pages about container preloading and information can get out of sync, so review and improve both pages.
=> Sync information about container preloading

source/reference-manual/linux/linux-disk-encryption.rst, source/reference-manual/linux/linux.rst
Add missing documentation to cover disk encryption on lmp.
=> rm: linux: add page for disk encryption support

source/user-guide/account-management/account-roles.rst
Changed description of permissions in table to decrease length. This is simpler and potentially less messy than addressing this via css. Kept "Managing" descriptors for members and teams to avoid confusion with identifying table column/rows at first glance.
Doc QA: Checked html rendering, no issues.
No Jira task to connect to.
fixed table fit issues
=> Fix account-roles table width

source/reference-manual/security/authentication-xilinx.rst
Extend instructions to better cover the usage and integration with LmP (when not building outside LmP).
=> rm: authentication-xilinx: extend integration with LmP

source/index.rst
UG before RM is standard convention
=> move ug listing

source/getting-started/signup/index.rst
General cleanup and revisiting page.
I *think* I like the section title changes, but if there are any objections, I do not mind keeping them as they were.
=> GS signup fixes

source/getting-started/register-device/index.rst
Fixed trademark and heading issues. Changed markdown to use semantic newlines. Reduced wordiness.
QA Steps: Ran linkcheck. Final run an issue on a different page with an external link showed up, this is an external issue and can be ignored. Rendered and checked html output for correct visual formatting. Linted.
No Jira issues to tag, routine cleanup.
Routine cleanup.
=> Cleanup register-device getting started page

source/getting-started/flash-device/index.rst
Cleanup tasks focused on style rules and text cleanup. We may need changes to content to bring it up to date. Screenshots show older GUI colors, but should largely be the same.
QA Steps: Ran vale to lint, and then linkcheck and checked rendered output. No issues should be present.
No Jira task to link to, as this is routine cleanup of the docs.
General cleanup, validity of steps may need to be checked.
=> Cleanup the flashing device getting started guide

.vale.ini
`.vale.ini` was updated to use Fio-style v1.2.0, which adds AWS and TLS to the acronym exceptions list.
QA Steps: ran vale sync and tested against files.
No issue to reference, general maintenance.
General maintenance/upkeep, no changes to content
=> Update Fio-style to v1.2.0

source/index.rst, source/reference-manual/factory/event-queues.rst, source/reference-manual/security/cert-rotation.rst, source/reference-manual/security/ota-security.rst, source/user-guide/cert-rotation.rst
=> rm: Add documenation for certificate rotation

source/conf.py
Extended copyright range in `source/conf.py`.
No QA steps performed.
No issues to link.
=> Extend copyright range to 2023

source/reference-manual/troubleshooting/troubleshooting.rst
=> rm: faq: include instructions to replace 'fio' user

source/reference-manual/security/secure-elements/secure-element.tpm.rst, source/reference-manual/security/security.rst
Instructions for using TPM2 devices with LmP.
=> rm: security: add page for tpm2 hsm support

README.md
=> Gh update readme

source/user-guide/offline-update/offline-update.rst
Update the doc on the offline update with details related to boot firmware update and rollback.
=> ug: op: Update doc with details on rollback

source/getting-started/install-fioctl/index.rst, source/reference-manual/factory/api-access.rst, source/reference-manual/factory/event-queues.rst, source/reference-manual/factory/sboms.rst, source/reference-manual/ota/static-deltas.rst, source/reference-manual/testing/fiotest.rst, source/user-guide/cert-rotation.rst, source/user-guide/custom-ci/custom-ci-for-apps.rst, source/user-guide/el2g.rst
Only focused on updating trademark for Fioctl.
=> Update fioctl copyright

source/reference-manual/boards/kv260.rst
Add steps for erasing uboot environment on QSPI.
=> rm: kv260: add steps for erasing ubootenv

source/user-guide/lmp-customization/lmp-customization.rst
=> ug: lmp customization: add steps to enable ntp

source/reference-manual/linux/linux-update.rst
=> rm: improve information on lmp customer factory update

source/getting-started/install-fioctl/index.rst
This got dropped on the last merge but it still needed in some cases, so re-add the lines.
=> gs: fioctl: re-include git config commands

source/tutorials/working-with-tags/following-specific-tag.rst, source/user-guide/troubleshooting/troubleshooting.rst
Added notes in troubleshooting/FAQ and tutorial section on tags.
Checked rendered html, no issues spotted.
This commit addresses FFTK-1897
Adds frequently requested information.
We can add/move the info elsewhere or expand on it, if need be.
=> Add note about allowed characters for devices/tags

source/reference-manual/linux/development-tags.rst
Extend description of existing development tags.
Add additional development tags and details about how patches should be cherry-picked in the right way.
=> rm: linux: development-tags: add new tags

source/reference-manual/ota/production-targets.rst
Add new options to roll out a wave to production devices.
This also cleans content on that legacy page before any additions.
=> Waves rollout updates

source/reference-manual/linux/linux-kernel.rst
Add instructions about Xenomai4
=> linux-kernel: add instructions about Xenomai4

source/reference-manual/security/secure-boot-ti-am62x.rst, source/reference-manual/security/security.rst
=> am62x: secure boot: document the TI key writer

source/tutorials/getting-started-with-docker/building-your-container.rst, source/tutorials/getting-started-with-docker/cloning-container-repository.rst, source/tutorials/getting-started-with-docker/extra-commands.rst, source/tutorials/getting-started-with-docker/getting-started-with-docker.rst, source/tutorials/getting-started-with-docker/gs-docker-compose.rst, source/tutorials/getting-started-with-docker/gs-dockerfile.rst, source/tutorials/getting-started-with-docker/gs-httpd.rst, source/tutorials/getting-started-with-docker/gs-summary.rst
The Docker tutorial section had a number of style and grammar fixes applied. Information was also updated to reflect the usage of the Fast First Target, so mentions of build wait time was removed, as well as the separate branches.
QA Steps: Content was reviewed for correctness where possible, however a detailed follow along was skipped. Linter was ran. HTML output was checked for correct rendering. No issues were spotted.
This commit addresses FFTK-2511
This commit applies to FFTK-2510
This commit applies to FFTK-2430
This commit applies to FFTK-988
see commit comment and related issues.
_This could include potential issues, rational for …
=> Cleanup docker tutorial

source/reference-manual/boards/am62xx-sk-prepare.rst, source/reference-manual/boards/am64xx-sk-prepare.rst
It helps building for the gp variant avoiding some
pre-flash files manipulations.
=> am6[2|4]xx-sk-prepare: add note about the existing variants

source/reference-manual/security/secure-elements/secure-element.tpm.rst, source/user-guide/lmp-customization/lmp-customization.rst
=> Feedback from pinned messages

source/reference-manual/qemu/qemu-instructions.template
Removed mention of using Fioctl. Instead directed towards the Targets tab as mentioned (and now linked to) in the flashing section of the getting started guide.
QA Steps: checked rendered output and link. No issues.
No related issues to note, quick fix.
=> Update QEMU section for downloading artifacts

source/reference-manual/remote-access/wireguard.rst
=> remote-access: more troubleshooting for wireguard

source/reference-manual/linux/building-sdk.rst, source/reference-manual/linux/linux-building.rst, source/reference-manual/linux/linux-distro.rst, source/reference-manual/linux/linux-extending.rst
Include how to change (append and remove) and examples for DISTRO_FEATURES, IMAGE_FEATURES, and MACHINE_FEATURES.
any idea on what else to add?
=> Distro features

source/reference-manual/linux/linux-extending.rst
Add a note that changing those variables result in significant change to the final artifact
=> rm: linux-extending: Add important note to FEATURES

source/getting-started/signup/index.rst
Added to the getting started guide under selecting platform.
QA Steps: Checked rendered html.
This commit addresses FFTK-2619
=> Add x86-64 note to clear up lack of details

source/reference-manual/qemu/qemu-instructions.template
Additional information was added to explicitly let readers know where the resizable images can be located. A typo was fixed, and a note on artifact names was also added.
QA steps: Checked rendered html
This addresses FFTK-2617
=> Add information on qcow2 artifact

.vale.ini
Update the vale config to use the latest release of the style rules.
QA Steps: Synced vale and ran against markdown file.
*   [ ] Merge (pending reviews)
*   [ ] Draft
*   [ ] Avoid changing any header associated with a link/reference.
*   [ ] Match tone and style of page/section.
*   [ ] View HTML in a browser to check rendering.
*   [ ] Use [semantic …
=> Update vale style rules

source/getting-started/signup/index.rst
Language was changed to note that the image is used by qemu rather than with a qemu machine, per feedback on PR #572
Addresses feedback
=> Update note on x86 qemu in getting started

source/reference-manual/linux/linux-dev-mode.rst, source/reference-manual/linux/linux.rst
Add a brief description on what could be DEV_MODE
~Please, don't merge yet as I'm still building on the factory~. Build tested! The text is ready to review.
Oh, and please let me know if you have another idea on how to use dev mode.
=> rm: linux: Add DEV_MODE description

source/reference-manual/security/ff-security-summary.rst, source/reference-manual/security/offline-keys.rst
Update TUF user guide with multi-key support
Task: 
- https://foundriesio.atlassian.net/browse/FFTK-2506
User stories:
- https://foundriesio.atlassian.net/browse/FFTK-1203
- https://foundriesio.atlassian.net/browse/FFTK-1204
=> Update TUF user guide with multi-key support

source/user-guide/account-management/subscription-and-billing.rst
Changing credit card used was mentioned under payment and billing on the subscription and billing page. As changing the card used is a frequent request, the hope is that by explicitly adding "credit card" it will be more likely to come up during a search of the docs.
QA Steps: Linter, linkcheck, and viewed rendered html. No issues to report.
This commit addresses FFTK-2734  
This commit applies to FFTK-2729
*   [ ] Draft
_Very small addition. Adds mention of "credit card" to increase findability of info_
*   [x] Avoid changing any header associated with a …
=> Add mention of credit card to billing

source/reference-manual/qemu/arm-substitutions.inc, source/reference-manual/qemu/arm64-substitutions.inc, source/reference-manual/qemu/qemu-instructions.template, source/reference-manual/qemu/riscv64-substitutions.inc, source/reference-manual/qemu/x86_64-substitutions.inc
The command provided do not work on MacOS. Following the proposed solution
=> (Booting Graphically) add command to run image using QMEU with graphic option on MacOS 

source/reference-manual/linux/linux-building.rst
lmp-manifest is now a singl branch repo (main)
=> local build: lmp-manifest devel branch removed

source/index.rst, source/release-notes/release-notes.rst, templates/release-notes.rst
Sidebar entry added for `source/release-notes/release-notes.rst`. Template file also added.
This commit will allow review of the format.  
After being merged, content will be added prior to v92.
QA Steps: built and checked html, no issues noted.
This commit addresses FFTK-2537
*   [ ] Draft
*   [x] Match tone and …
=> Add release note section

source/user-guide/el2g.rst
=> Revert "Revert 611 main"

source/reference-manual/security/imx-generic-custom-keys.rst
Toradex PIDs are not included in fuse/close scripts by default, so add a note for it.
=> rm: security: secure machines: add information about Toradex PIDs

source/reference-manual/linux/linux-lmp-fs.rst, source/reference-manual/ota/aktualizr-lite.rst, source/reference-manual/security/device-gateway.rst, source/reference-manual/security/secure-boot-imx-habv4.rst, source/reference-manual/security/secure-boot-uefi.rst, source/tutorials/customizing-the-platform/customizing-the-platform.rst, source/user-guide/troubleshooting/troubleshooting.rst
Instances where the documentation stated something was or was not recommended, and not following the recommends fall outside of support, were clarified to state a lack of support.
QA Steps: rendered and quickly checked html output
No issues to link
*   [ ] Draft
*   [x] …
=> Clarify recommend statements

source/getting-started/install-fioctl/index.rst, source/user-guide/account-management/team-based-access.rst, source/user-guide/fioctl/index.rst
Added a note in the getting started guide, a slightly more detailed note in the user guide, and an additional somewhat related note in team based access.
QA: information will be verified during PR process. Rendered html checked, no errors spotted. No linter errors that need correcting.
This commit addresses issue FFTK 2905
Short additions regarding Fioctl updating!
I totally may have gotten something wrong, so please verify my understanding! I also feel like there may be additional information which could be added.
=> Add info about fioctl auto update

source/reference-manual/boards/am62xx-sk.rst
Previous commit bbf04f4 seems to have reverted or incorrectly "resolved" changes introduced in 20cc39c. This commit adds the missing information.
QA Steps: checked rendered html, no issues found.
No issues to link to.
*   [ ] Draft
*   [x] …
=> Fix board flashing instructions

source/release-notes/release-notes.rst
Release notes for the v92 release.
=> release-notes: add release notes for the v92 release

source/reference-manual/security/device-gateway.rst
Minor style-guide related changes made to page.
Section headers changed, references kept the same.
QA Steps: checked rendered output in browser, ran linter and linkcheck.
*   [ ] Draft
*   [x] Run `make linkcheck`.
*   [x] View HTML in a …
=> Cleanup device-gateway reference-manual page

source/reference-manual/linux/linux-update.rst, source/release-notes/rn_v92.inc
Links added to release notes, as well as a link to the release notes from the updating LmP manual page.
This takes the place of docs PR #647, but avoids dealing with a merge conflict.
*   [ ] Draft
*   [ ] Avoid changing any header associated with a link/reference.
*   [ ] Match tone and style of page/section.
*   [ ] View HTML in a browser to check …
=> Add links to release notes for v92

source/release-notes/rn_v92.inc
=> rn: v92: add note about dropping imx8mp mfgtool u-boot.itb requirement

source/reference-manual/security/cert-rotation.rst
Applied style guide rules. Only a few minor changes were done.
Viewed rendered output, and ran linter.
=> Cleanup cert-rotation security rm page

source/reference-manual/security/ff-security-summary.rst
Minor style-guide related changes made to page.
QA Steps: checked rendered output in browser, ran linter and linkcheck.
=> Cleanup ff-security-summary reference-manual page

source/conf.py
Updated year.
No QA steps done.
No issues to link, minor change.
=> Update copyright notice to extend into 2024

source/reference-manual/ota/aktualizr-lite.rst
Fixed typo which was preventing intended rendering.
QA: viewed output, no issues.
No related issues to link.
=> Fix `` typo on ota/aktualizr-lite page

source/reference-manual/security/secure-boot-imx-ahab.rst, source/reference-manual/security/secure-boot-imx-habv4.rst
Minor changes for readability and style made to the two pages.
QA Steps: checked rendered output, no issues noticed. Ran linter.
=> Cleanup secure-boot imx security rm pages

source/user-guide/troubleshooting/troubleshooting.rst
=> fioctl/git/Troubleshooting: add tip to provide helpful info to Troubleshooting the gitconfig

source/reference-manual/ota/aktualizr-lite.rst
Brief warning added as single line.
QA steps: viewed rendered html.
This commit addresses FFTK-2965
=> Add warning for aktualizr-lite update

source/getting-started/signup/index.rst, source/porting-guide/pg-introduction.rst, source/reference-manual/factory/factory-sources.rst, source/reference-manual/security/device-gateway.rst, source/reference-manual/security/revoke-imx-keys.rst, source/user-guide/device-gateway-pki/device-gateway-pki.rst
Links all updated to `https://support.foundries.io`.
QA Steps: Built site, no errors.
No issues to link, minor issue reported over Slack.
=> Fix customer support request links

source/reference-manual/security/secure-boot-ti-am62x.rst
Changes made for style, readability, and clarity.
QA steps: ran linter, and viewed rendered output.
No issues found.
We may want to further review the page to make sure information is up to date and accurate.
=> Cleanup secure-boot ti-am62x security rm page

source/reference-manual/security/secure-boot-uefi.rst
Small changes made, focusing on style and readability.
QA Steps: Checked rendered output. No issues spotted.
=> Cleanup security-secure-boot-uefi

source/reference-manual/security/factory-keys.rst
Only a few changes made for grammar or readability.
QA Steps: used linter, spellcheck, and viewed rendered output.
*   [ ] Draft
*   [x] View HTML in a browser to check rendering.
*   [x] Use [semantic …
=> Cleanup security-build-time-crypto-keys

source/reference-manual/security/revoke-imx-keys.rst
Applied style rules, cleaned up for clarity and readability.
QA Steps: ran linter, spellcheck, and checked rendered output.
This commit is to replace the now closed/canceled PR #664.
This applies to FFTK-2795
This replaces PR #664 which was approved but had a merge conflict.
=> Cleanup of security-revoking srk keys

source/reference-manual/boards/am62xx-sk.rst
Adjust flashing instructions so eMMC is explicitly used for flashing.
=> rm: am62xx: adjust flashing instructions

source/user-guide/submodule/submodule.rst
Fixed the header typo, in addition to a few other small changes to improve readability.
QA Steps: Built site, edited with spellcheck and linter.
No issue, small fix.
=> Fix typo in submodule section title

source/reference-manual/security/secure-elements/secure-element.050.rst
Edited to improve readability and to follow style guide.
QA Steps: Ran linter and spellcheck in editor. Viewed rendered output.
This commit applies to FFTK 2795
Part of ongoing cleanup effort.
=> Cleanup edge-lock-se05x page

source/reference-manual/security/boot-software-updates-imx8qm.rst
Cleaned up for spelling, grammar and readability.
Checked output for correct rendering, no issues spotted. Reviewed linter findings.
=> Cleanup security-boot-software-updates-imx8qm

source/reference-manual/testing/fiotest.rst, source/reference-manual/testing/lmp-testplan.rst, source/reference-manual/testing/testing-architecture.rst, source/reference-manual/testing/testing.rst
Applied style guide recommendations and edited to increase readability.
QA Steps: linter and spellcheck used in editor. Checked rendered output for correctness. No issues found.
This commit addresses FFTK-2796
This commit applies to FFTK-1702
In addition to cleanup, also added an overview summary to the title/toc page for the section.
=> Cleanup testing reference manual section

source/reference-manual/ota/aktualizr-lite.rst
=> ota: aktualizr-lite: add allowed values for storage_watermark

source/user-guide/custom-sota-client.rst
Extend the custom sota client doc with info on new modes it supports.
=> ug: Update the custom sota client doc

source/index.rst, source/user-guide/ip-protection/ip-protection.rst, source/user-guide/lmp-customization/linux-extending.rst
This brings a new section on IP Protection.
=> UG: Introduce IP Protection

source/reference-manual/security/offline-keys.rst, source/user-guide/offline-update/offline-update.rst
=> Update the doc about the offline update

source/user-guide/offline-update/offline-update.rst
* [ x Sign commit with your gpg key (`-S, --gpg-sign`).
=> Fix and update aklite-offline return codes based on v93 behavior

source/tutorials/working-with-tags/following-specific-tag.rst
Add note limiting tag changes to the compatible targets. New tag has to contain all apps that are present on the target tagged with old tag.
Adds explanation to limitations when changing device tags.
=> tutorials: Add note to following tag page

source/glossary/index.rst, source/reference-manual/security/ff-security-summary.rst, source/user-guide/account-management/account-roles.rst
Security terms added, with links to pages with any significant discussion/use of the term.
QA: Ran linkcheck and linter. Viewed rendered output.
This commit addresses FFTK-3009
Terms from spread sheet added, with additional info added where appropriate. Also added links to pages dealing with the terms/topics when possible. A couple refinements to other glossary terms. 
There is likely additional terms we could add, which can either be done as part of this PR if small, or as a …
=> Add Security terms to glossary

source/user-guide/custom-sota-client.rst
Fixed broken ref.
QA Steps: Checked rendered HTML, no issues.
No issue tracking, minor fix.
Minor fix
=> Fix broken ref on custom-sota-client page

.vale.ini
Fio-docs linter rules set to use the latest package. Also set acronym rule to warning over error.
QA: Ran linter, no issues.
This commit addresses FFTK-3141
=> Update style rules to latest package

source/reference-manual/factory/factory-definition.rst, source/reference-manual/factory/sboms.rst
* [ x ] Merge (pending reviews)
Documenting new variable for customers wanting to disable SBOMs from container builds.
https://foundriesio.atlassian.net/browse/FFTK-3134
=> rm: Add details of new DISABLE_SBOM container CI variable

source/user-guide/offline-update/offline-update.rst
=> ug: offline-update: Update doc with more info on app fetching config

source/user-guide/qemu/arm-substitutions.inc, source/user-guide/qemu/arm.rst, source/user-guide/qemu/arm64-substitutions.inc, source/user-guide/qemu/arm64.rst, source/user-guide/qemu/generic-prepare.template, source/user-guide/qemu/qemu-instructions.template, source/user-guide/qemu/riscv64.rst, source/user-guide/qemu/x86_64-substitutions.inc, source/user-guide/qemu/x86_64.rst
Changes made for consistency, readability, and to address missing information such as version info.
QA Steps: checked for correct output.
This commit addresses FFTK-3196
Combines issues mentioned in documentation Slack channel with those found while
in the process.
=> Fix qemu section issues

source/user-guide/lmp-customization/linux-extending.rst
Typos fixed and style rules applied, other small changes to increase readability.
QA Steps: Checked rendered HTML, no issues seen. Ran linter within editor, no new issues discovered.
No related ticket, quick fix.
Discovered small typo while working on something else, did additional cleanup at the same time.
=> Cleanup lmp-extending user guide

release-notes/rn_v92.md, release-notes/rn_v93.md
Copied release notes to new folder at repo root, and converted to Markdown.
QA: Viewed partially rendered markdown locally, GitHub flavored Markdown means a full check locally is not possible.
This commit applies to FFTK-3255
This will make it easier to properly test further work on FFTK-3255, which is decoupling the release notes from the documentation. Follow up PR will remove the rst, and replace sidebar release note links to point to the GitHub repo. This will allow for …
=> Add release notes to separate folder

source/conf.py, source/reference-manual/security/secure-elements/secure-element.tpm.rst, source/user-guide/custom-sota-client.rst
Maintenance task, addressed linkcheck errors.
QA: Linkcheck
No related task, general upkeep of the docs.
=> Fix broken links

source/user-guide/custom-ci/custom-ci-for-apps.rst
Basic cleanup and readability changes. Of note:
* fixed numbering
* example for user GitHub URL changed, replacing "foundriesio" with "<your account>"
* broken reference to top of page removed, not needed.
* added `ci:read-update` to list of required token scopes.
QA Steps: Ran linter, linkcheck, and checked rendered output in browser.
No related tasks, quick fix/cleanup.
_This …
=> Cleanup custom ci to build compose app targets

scraper.json
Config for `docs-scraper`, which populates the search index.
QA Steps: n/a
No related task.
=> Add config file for search scraper

source/conf.py
Linkcheck was reporting a valid anchor as a broken link. Added line instructing linkcheck to ignore anchor.
QA Steps: ran a clean linkcheck, no issues found.
No related task, quick fix.
=> Fix linkcheck error

.vale.ini
Updated to 2.1.0 which addresses current trademark guidelines for FoundriesFactory.
QA: Synced Vale and ran against `README.md`, which worked as intended.
This commit applies to FFTK-3429
Maintenance task, does not effect content.
=> Update linter style package

.vale.ini
Updating to latest release of the fio-style rules.
QA: checked that vale was able to sync and pull latest package.
This commit applies to FFTK-3430
Routine task, does not have a direct effect on content.
=> Update linter rules to v2.2.0 release

source/reference-manual/docker/restorable-apps.rst
Updated, with link to the composeapp repo.
QA: ran build and checked output in browser. Ran linkcheck locally. No issues to report.
No related tasks, small fix mentioned via internal channel.
=> Replace Skopeo with composeapp

release-notes/rn_v94.md
Release note changes for the v94.1 stable release.
=> rn_v94.md: add changes for v94.1

.vale.ini
This commit updates the linter rule set.
This commit applies to FFTK-3450
Routine update to linter rules.
=> Update to fio-style v2.3.0

source/index.rst
Changes to intro/product summary blurb made to follow Marketing messaging guidelines. Link at top no goes to product page of the foundries.io website.
Note that other requested changes which involve the sidebar, header, or footer will be handled in a separate PR.
QA: Ran linkcheck and viewed built HTML.
This commit addresses FFTK-3449
_This could include potential issues, …
=> Update title page to reflect messaging guidelines

source/reference-manual/linux/linux-disk-encryption.rst
Document the variables that control CI disk encryption.
=> rm: CI LUKS encryption

.vale.ini
Now using fio-style v2.4.0, to include rule suggestion that catches extra spaces between words and sentences.
QA: tested that vale was able to sync package.
No related open tasks/issues.
Maintenance task
=> Update linter rule package

source/_templates/layout.html, source/conf.py, source/index.rst
Link added to home page to FoundriesFactory product page. Logo now linkes to Foundries homepage.
Button added to home page to book a demo.
QA Steps: checked links, and that the output renders as intended.
This commit addresses MKT-799, "Add Foundries.io liinks to Docs pages"
Adds requested links
=> Add CTA buttons/links

source/reference-manual/security/secure-boot-uefi.rst
Document the Secure Key revocation process.
=> rm: security: UEFI Secure Boot Key Revocation

.vale.ini, source/reference-manual/security/secure-elements/secure-element.050.rst, source/tutorials/compose-app/compose-app-applications.rst, source/user-guide/account-management/account-roles.rst, source/user-guide/account-management/team-based-access.rst, source/user-guide/custom-ci/custom-ci-for-apps.rst, source/user-guide/custom-ci/custom-ci-for-rootfs.rst, source/user-guide/custom-sota-client.rst, source/user-guide/device-gateway-pki/device-gateway-pki.rst, source/user-guide/lmp-device-auto-register/lmp-device-auto-register.rst, source/user-guide/rotating-cert.rst
Reviewed results from vale, and expanded where appropriate.
The Fioctl install section and the Troubleshooting guide were not addressed, so as to avoid having to deal with a merge conflict from recently merged PRs, and will be addressed separately.
Ran build and checked output for errors.
This commit applies to issue FFTK-2012, "…prefix acronyms…"
_This could include potential …
=> Expand acronyms

source/user-guide/fioctl/index.rst, source/user-guide/troubleshooting/troubleshooting.rst
Expanded acronyms, and applied semantic newlines on the troubleshooting page to make editing easier.
Checked rendered output for errors.
This commit applies to issue FFTK-2012, "…prefix acronyms…"
=> Expand additional acronyms

source/reference-manual/security/secure-boot-uefi.rst
=> Fix syntax for UEFI_SIGN_ENABLE

source/reference-manual/security/device-gateway.rst
Added sentence stating what is created. Minor cleanup, and moved the how-to content above the terminology section.
QA: Checked rendered HTML, no issues.
This commit addresses issue FFTK-1469, "… clarify that the fioctl command creates…"
=> Clarify fioctl PKI ca create command

README.md, source/index.rst
Added tip alerting readers that our docs are open. Also update `README.md` contribution guidelines.
Built docs and viewed output.
This commit addresses FFTK-1788, "…encourage customer contributions…"
=> Encourage public contributions to documentation

source/conf.py
Added `source.foundries.io` addresses to the ignore list as they were being erroneously marked as errors by linkcheck.
QA: ran linkcheck and built docs locally.
No associated issue, small fix.
=> Add link to ignore list

source/_static/csv/supported-boards.csv
Removed from csv, only reference found via grep.
QA: ran html build locally, no issues.
This commit addresses Jira issue FFTK-3837, "Remove RPi3 machine…"
=> Remove rpi3-32 from list

source/reference-manual/ota/configuring.rst
=> rm: add information about config files precedence

source/user-guide/offline-update/offline-update.rst
There are some cases that need to be considered when providing a long term (>1y) offline update bundle, so cover this here.
=> ug: offline-update: include table for offline bundle x tuf rotation

source/reference-manual/ota/update-rollback.rst, source/user-guide/custom-sota-client.rst
=> ug: Re-organize aklite CLI commands documentation

source/index.rst, source/reference-manual/index.rst, source/tutorials/index.rst, source/user-guide/index.rst
Section overview pages providing a brief overview/intro were added for the main sections.
QA: ran build, checked links, no issues found.
This commit addresses issue FFTK-1973, "Add section overview pages"
Also updated home page info to reflect rebranding.
=> Add section overview pages

source/user-guide/lmp-customization/lmp-customization.rst
Added info from `meta-lmp` PR 1593.
QA steps: ran build and checked rendered output.
This commit addresses FFTK-3843, "Update docs on changing default user"
=> Update info on changing default user

source/reference-manual/security/secure-boot-ti-am62x.rst
The directory changed in Scarthgap release.
=> RM: security: Fix path for ti keys directory

README.md
Added details for how visual assets in `_static` are to be organized.
QA: edited with linter plugin.
This commit addresses issue FFTK-3943, "…organization scheme for `_static`"
=> Add organization scheme for _static to readme

source/reference-manual/linux/building-sdk.rst, source/reference-manual/linux/linux-dev-mode.rst, source/reference-manual/linux/linux-distro.rst, source/reference-manual/linux/linux-update.rst, source/user-guide/lmp-customization/linux-building.rst, source/user-guide/lmp-customization/linux-extending.rst
Updated references to Yocto release. For links to Yocto Project docs, using '5.0.8'.
QA: ran build. Linkcheck will be done after opening PR; running locally is not possible using company machine.
This commit applies to FFTK-3230, "Review and add release notes for docs"
=> Update kirkstone refs to scarthgap

source/_static/csv/supported-boards.csv, source/user-guide/flashing/flashing.rst, source/user-guide/flashing/rb3gen2.rst
Flashing page added so as to show up in search results. Board also added to the supported-boards file.
QA: ran build and linter. No issues to report.
No associated issue, quick fix.
=> Add rb3g2 board and flashing link

release-notes/rn_v95.md
=> RN: Fix typos for v95

release-notes/rn_v95.md
=> rn: v95: append information about x86 build error

source/reference-manual/linux/linux-update.rst
Info updated and a dropdown with an explanation added.
QA: ran build locally and checked output for accurate rendering.
This commit addresses issue FFTK-4163, "Update info on lmp-manifest…"
=> Update info on lmp-manifest tag use

source/conf.py
=> Disable switcher check
